

DROP SEQUENCE SEQ_AUTO_INCRMENT_ONE;

CREATE SEQUENCE SEQ_AUTO_INCRMENT_ONE
increment BY 1
start with 1
minvalue 1
maxvalue 999999999
;
/*更改序列
ALTER SEQUENCE SEQ_AUTO_INCRMENT_ONE
increment BY 2
--start with 1 --ERROR有错
minvalue 1
maxvalue 999999999
;
--*/
--SELECT SEQ_AUTO_INCRMENT_ONE.NEXTVAL FROM DUAL;

--INSERT INTO A_TB_TEST(iIndex) values(SEQ_AUTO_INCRMENT_ONE.NEXTVAL);
