--/*
DROP TABLE tmp_tb;
CREATE TABLE tmp_tb(order_num INTEGER, CREATE_TIMEU DATE, OPER_CR VARCHAR2(200));
--*/

CREATE OR REPLACE TRIGGER tr_update_equipment
  AFTER INSERT
  ON C##Fusion.TM_TASKU
  FOR EACH ROW --说明创建的是行触发器
  --如果没加是说明是语句级触发吗？如果没加是不能使用commit的
DECLARE
  I_SRM01_TASK_COUNT INTEGER;
  I_SRM02_TASK_COUNT INTEGER;
  I_CR_ALARM_STATUS INTEGER;
  pragma autonomous_transaction; --让oracle触发器知道这是自定义事务处理
BEGIN
  SELECT COUNT(TASK_STATUSU) INTO I_SRM02_TASK_COUNT FROM C##Fusion.TM_TASKU WHERE CAN_OPERATION_EQUIPMENTU=',SRM02,' AND TASK_STATUSU !='2' AND TARGET_LOCATION_CODEU IN ('3129','3138'); --TASK_STATUSU为2代表已完成
  SELECT COUNT(TASK_STATUSU) INTO I_SRM01_TASK_COUNT FROM C##Fusion.TM_TASKU WHERE CAN_OPERATION_EQUIPMENTU=',SRM01,' AND TASK_STATUSU !='2' AND TARGET_LOCATION_CODEU IN ('3129','3138');
  IF I_SRM01_TASK_COUNT > I_SRM02_TASK_COUNT THEN
    SELECT EQUIPMENT_STATUS_CODEU INTO I_CR_ALARM_STATUS FROM EM_EQUIPMENTU WHERE EQUIPMENT_CODEU='SRM02';
    IF I_CR_ALARM_STATUS = 1 THEN
      UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=0,REMARKU='定时器修改SRM01于'|| TO_CHAR(SYSDATE, 'yy-mm-dd hh24:mi:ss') WHERE EQUIPMENT_CODEU='SRM01'; --一号堆垛机禁用出库
      UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=1,REMARKU='定时器修改SRM02于'|| TO_CHAR(SYSDATE, 'yy-mm-dd hh24:mi:ss') WHERE EQUIPMENT_CODEU='SRM02'; --二号堆垛机启用出库
    ELSE
      UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=1,REMARKU='定时器修改SRM01、SRM02于'|| TO_CHAR(SYSDATE, 'yy-mm-dd hh24:mi:ss') WHERE EQUIPMENT_CODEU IN ('SRM01','SRM02'); --二号堆垛机启用出库
    END IF;
    INSERT INTO tmp_tb SELECT COUNT(*),SYSDATE,'启用二号堆垛机，任务数'||I_SRM02_TASK_COUNT||'，禁用其他堆垛，任务数：'||I_SRM01_TASK_COUNT||'，设备状态为:'||I_CR_ALARM_STATUS FROM C##Fusion.TM_TASKU;
  ELSE
    SELECT EQUIPMENT_STATUS_CODEU INTO I_CR_ALARM_STATUS FROM EM_EQUIPMENTU WHERE EQUIPMENT_CODEU='SRM01';
    IF I_CR_ALARM_STATUS = 1 THEN
      UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=1,REMARKU='定时器修改SRM01于'|| TO_CHAR(SYSDATE, 'yy-mm-dd hh24:mi:ss') WHERE EQUIPMENT_CODEU='SRM01'; 
      UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=0,REMARKU='定时器修改SRM02于'|| TO_CHAR(SYSDATE, 'yy-mm-dd hh24:mi:ss') WHERE EQUIPMENT_CODEU='SRM02';
    ELSE
      UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=1,REMARKU='定时器修改SRM01、SRM02于'|| TO_CHAR(SYSDATE, 'yy-mm-dd hh24:mi:ss') WHERE EQUIPMENT_CODEU IN ('SRM01','SRM02'); --二号堆垛机启用出库
    END IF;
    INSERT INTO tmp_tb SELECT COUNT(*),SYSDATE,'启用一号堆垛机，任务数'||I_SRM01_TASK_COUNT||'，禁用其他堆垛，任务数：'||I_SRM02_TASK_COUNT||'，设备状态为:'||I_CR_ALARM_STATUS FROM C##Fusion.TM_TASKU;
  END IF;
  COMMIT;
END;