--/*
DROP TABLE tmp_tb;
CREATE TABLE tmp_tb(order_num INTEGER, CREATE_TIMEU DATE, OPER_CR VARCHAR2(50));
--*/

CREATE OR REPLACE TRIGGER tr_update_equipment
  AFTER INSERT
  ON C##Fusion.TM_TASKU
  --FOR EACH ROW --说明创建的是行触发器
  --如果没加是说明是语句级触发吗？
DECLARE
  I_CR01_TASK_COUNT INTEGER;
  I_CR02_TASK_COUNT INTEGER;  
BEGIN
  SELECT COUNT(TASK_STATUSU) INTO I_CR02_TASK_COUNT FROM C##Fusion.TM_TASKU WHERE CAN_OPERATION_EQUIPMENTU=',CR02,' AND TASK_STATUSU !='2' AND LENGTH(TARGET_LOCATION_CODEU)=6; --TASK_STATUSU为2代表已完成
  SELECT COUNT(TASK_STATUSU) INTO I_CR01_TASK_COUNT FROM C##Fusion.TM_TASKU WHERE CAN_OPERATION_EQUIPMENTU=',CR01,' AND TASK_STATUSU !='2' AND LENGTH(TARGET_LOCATION_CODEU)=6;
  IF I_CR01_TASK_COUNT > I_CR02_TASK_COUNT THEN
    UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=0 WHERE EQUIPMENT_CODEU='CR01'; --一号堆垛机禁用出库
    UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=1 WHERE EQUIPMENT_CODEU='CR02'; --二号堆垛机启用出库
    INSERT INTO tmp_tb SELECT COUNT(*),SYSDATE,'启用二号堆垛机，禁用其他堆垛' FROM C##Fusion.TM_TASKU;
  ELSE
    UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=1 WHERE EQUIPMENT_CODEU='CR01'; 
    UPDATE EM_EQUIPMENTU SET IS_CAN_OUTBOUNDU=0 WHERE EQUIPMENT_CODEU='CR02';
    INSERT INTO tmp_tb SELECT COUNT(*),SYSDATE,'启用一号堆垛机，禁用其他堆垛' FROM C##Fusion.TM_TASKU;
  END IF;
END;