

SELECT * FROM WM_STORAGEU WHERE FACTURER_NAMEU LIKE '%南阳双龙%'AND LENGTH(LOCATION_CODEU)=8;

----添加配盘信息
SELECT * FROM BI_MATCH_PALLET_DETAILU
  WHERE MATCH_PALLET_CODEU IN
  (SELECT MATCH_PALLET_CODEU FROM BI_MATCH_PALLETU WHERE BRAND_CODESU='69010281617180001' AND MATCH_PALLET_CODEU LIKE '%1001%');

----查找库存中的厂商信息*************
----查找盘位、货位
SELECT * FROM WM_STORAGEU WHERE LOCATION_CODEU='101002';
SELECT * FROM WM_PALLETU WHERE IDU='028C2BD57E43874A81A78816ACF030CB';
SELECT * FROM WM_PALLETU WHERE PALLET_TYPE_NAMEU LIKE '%%' AND BRAND_NAMESU LIKE '%红旗渠（芒果）%';
SELECT * FROM WM_PALLETU WHERE IDU IN
(
SELECT DISTINCT PALLET_IDU FROM WM_STORAGEU WHERE FACTURER_CODEU NOT IN (SELECT BI_FACTURERU.FACTURER_CODEU FROM BI_FACTURERU)
);
SELECT * FROM WM_PALLETU WHERE IDU IN
  (SELECT DISTINCT PALLET_IDU FROM WM_STORAGEU WHERE LENGTH(LOCATION_CODEU)=6);
SELECT * FROM WM_STORAGEU WHERE PALLET_IDU IN
(SELECT IDU FROM WM_PALLETU WHERE PALLET_TYPE_NAMEU LIKE '%%' AND BRAND_NAMESU LIKE '%红旗渠（芒果）%');
----查找厂商时使用NOT IN时候，要注意值是否为null
SELECT * FROM BI_FACTURERU WHERE FACTURER_CODEU NOT IN
( 
  SELECT DISTINCT FACTURER_CODEU FROM WM_STORAGEU WHERE LENGTH(LOCATION_CODEU)=8 AND FACTURER_CODEU IS NOT NULL  --一定要考虑数值是否为null，不然得到的是错误的结果
);
SELECT * FROM BI_FACTURERU;

SELECT * FROM WM_PALLETU WHERE LENGTH(LOCATION_CODEU)=8 ORDER BY UPDATE_TIMEU DESC;
SELECT DISTINCT FACTURER_CODEU, FACTURER_NAMEU, LOCATION_CODEU FROM WM_STORAGEU WHERE LENGTH(LOCATION_CODEU)=8 AND FACTURER_NAMEU LIKE '%新郑金芒果%';
SELECT * FROM WM_PALLETU WHERE LOCATION_CODEU='02-21-01';
SELECT * FROM WM_PALLETU WHERE LENGTH(LOCATION_CODEU)=6 AND STORAGE_QUANTITYU != 0;
SELECT * FROM WM_STORAGEU WHERE LENGTH(LOCATION_CODEU)=6;
SELECT * FROM WM_STORAGEU WHERE PALLET_IDU IN
  (SELECT IDU FROM WM_PALLETU WHERE WM_PALLETU.BRAND_NAMESU='黄金叶(硬帝豪)');
SELECT * FROM WM_STORAGEU WHERE PALLET_IDU IN
  (SELECT IDU FROM WM_PALLETU WHERE WM_PALLETU.PALLET_TYPE_CODEU LIKE '%1003%' AND BRAND_NAMESU NOT LIKE '%红旗渠（芒果）%'); --卷接盘
SELECT * FROM WM_STORAGEU WHERE PALLET_IDU IN
  (SELECT IDU FROM WM_PALLETU WHERE WM_PALLETU.PALLET_TYPE_CODEU LIKE '%2002%' OR WM_PALLETU.PALLET_TYPE_CODEU LIKE '%2001%'); --箱皮
----查找库存中的厂商信息//////////////

----查找设备相关信息表
SELECT * FROM EM_EQUIPMENT_TASKU;
SELECT * FROM TM_OPERATION_EQUIPMENTU;
SELECT * FROM TM_WORK_EQUIPMENTU;


----////////机组呼叫，结单
SELECT * FROM WM_MACHINE_CALLU WHERE IDU='14A68CD10484004E8DB1E6F24D99E615';
SELECT * FROM BI_MATCH_PALLET_DETAILU WHERE MATCH_PALLET_CODEU IN
  (SELECT WM_MACHINE_CALLU.MATCH_PALLET_CODEU FROM WM_MACHINE_CALLU WHERE IDU='14A68CD10484004E8DB1E6F24D99E615');
SELECT * FROM WM_MACHINE_PALLETU  WHERE WORK_POSITION_NOU='101002';
SELECT * FROM WM_MACHINE_PALLET_DETAILU WHERE PALLET_POSITIONU IN
  (SELECT WM_MACHINE_PALLETU.PALLET_POSITIONU FROM WM_MACHINE_PALLETU  WHERE WORK_POSITION_NOU='101002');
SELECT * FROM WM_MACHINE_CALLU WHERE PRODUCTION_PLAN_NOU='P202008100012' AND MACHINE_CODEU='B205' AND TASK_NOU='8737';
----余料退库4,移交退料5
SELECT * FROM WM_MACHINE_CALLU WHERE CALL_TYPEU=4 OR CALL_TYPEU=5;
-----查询机组移交
SELECT * FROM WM_MACHINE_HANDOVER_DETAILU ORDER BY UPDATE_TIMEU DESC, TRANSFER_BILL_NOU;
SELECT RECEIVE_QUANTITYU, TRANSFER_QUANTITYU, TRANSFER_RATEU, TRANSFER_BILL_NOU, TO_CHAR(CREATE_TIMEU, 'yy-mm-dd hh24:mi:ss')
  FROM WM_MACHINE_HANDOVER_DETAILU 
  WHERE RECEIVE_QUANTITYU != TRANSFER_QUANTITYU ORDER BY UPDATE_TIMEU DESC, TRANSFER_BILL_NOU;
SELECT * FROM WM_MACHINE_HANDOVERU
   WHERE CURRENT_PLANU='P202008120024' ORDER BY CREATE_TIMEU DESC;
SELECT * FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_BILL_NOU =
  (SELECT TRANSFER_BILL_NOU FROM WM_MACHINE_HANDOVERU WHERE CURRENT_PLANU='P202008120024' AND ROWNUM=1)
  ORDER BY UPDATE_TIMEU DESC, TRANSFER_BILL_NOU;
-----//////////////
