
SELECT TASK_NOU,CALL_TYPEU,MACHINE_NAMEU,TEAM_NAMEU,MATCH_PALLET_NAMEU,PALLET_BARCODEU,SOURCE_LOCATION_CODEU
  ,IDENTITY_TAGU,UNLOCK_TAGU,STORAGE_TIMEU,CREATE_TIMEU,CALL_TIMEU,PICK_TIMEU,COMPLETE_TIMEU,OUTBOUND_TIMEU,MACHINE_CALL_STATUSU 
  ,EMPLOYEE_NAMEU,BRAND_NAMEU,PALLET_TYPE_NAMEU,AGVCODEU,PALLET_POSITIONU,PRODUCTION_PLAN_NOU
  FROM WM_MACHINE_CALLU WHERE (1=1)  ----******查询某班某班组某配盘呼叫记录
  --AND MACHINE_NAMEU LIKE '2#包装机%' 
  AND MACHINE_CODEU = 'B203'
  AND TEAM_CODEU = 1  
  AND BRAND_CODEU = '69010281692190001'
  AND PALLET_TYPE_CODEU = '1002NYSL'
  --AND PALLET_TYPE_NAMEU LIKE '%通用包%'
  AND (CALL_TYPEU = 0)-- OR CALL_TYPEU= 3)  ----///要料GetMateril=0,///取走空托盘TakeEmptyPallet=1,///余料退库ReturnMateril=2,///余料返库BackMateril=3,///移交退料MoveHandBackMateril=4,///移交要料MoveHandGetMateril=5,///缓存移料CacheMoveMateril=6
  --AND IDENTITY_TAGU IS NOT NULL
  ORDER BY CREATE_TIMEU DESC
  ; --->06-1月 -21  ，01-14-04
  
  

SELECT TO_CHAR(TB_A.STORAGE_TIMEU, 'yy-mm-dd hh24:mi:ss'), TB_A.* FROM WM_STORAGEU TB_A WHERE (1=1)
  --AND PALLET_IDU  IN
  --(SELECT IDU FROM WM_PALLETU WHERE 1=1 
  --  AND PALLET_TYPE_NAMEU LIKE '%通用包%' 
  --  AND BRAND_NAMESU LIKE '%黄金叶%'
  --)
  AND LENGTH(LOCATION_CODEU)=8 AND STORAGE_TIMEU < TO_DATE('2020-11-10 10:10:10',  'yyyy-mm-dd hh24:mi:ss')
  ORDER BY STORAGE_TIMEU;
  
  
  
