CREATE OR REPLACE FUNCTION F_A1
RETURN VARCHAR2
IS
  V_TEMP VARCHAR2(500);
  V_ROLE_ID_MES VARCHAR2(50);
  CURSOR CURS_TMP IS
    SELECT SYS_GUID() IDU,'RoledId',A1.MODULE_IDU,A1.IDU AS FUNCTION_IDU FROM SYS_FUNCTIONU A1 WHERE A1.NAMEU LIKE '%刷新%' OR A1.NAMEU LIKE '%查询%';
BEGIN
  SELECT IDU INTO V_ROLE_ID_MES FROM SYS_ROLEU WHERE ROLE_NAMEU = 'role_mes' AND ROWNUM=1; --如果INTO时候没数据，就会报错no data found，没必要再进行is null的判断了
  FOR ROW_FUNCTION IN CURS_TMP
  LOOP
    INSERT INTO SYS_PERMISSIONSU(IDU,ROLE_IDU,MODULE_IDU,FUNCTION_IDU) VALUES(ROW_FUNCTION.IDU,V_ROLE_ID_MES,ROW_FUNCTION.MODULE_IDU,ROW_FUNCTION.FUNCTION_IDU);
  END LOOP;
  RETURN '^_^';
  EXCEPTION WHEN OTHERS THEN
    RAISE;
END;
/
SET SERVEROUTPUT ON;
DECLARE
  V_TEMP VARCHAR2(50);
BEGIN
  V_TEMP := F_A1();
  DBMS_OUTPUT.PUT_LINE(V_TEMP);
  COMMIT;
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
