
drop user C##MES cascade;
create user C##MES identified by "mes@123456.mes";

alter system set resource_limit=true scope=both sid='*';  ----使用resource_limit及profile限制用户连接
drop PROFILE C##Mes_profile CASCADE;
create profile C##Mes_profile limit SESSIONS_PER_USER 1 FAILED_LOGIN_ATTEMPTS unlimited; ----新建一个user profile:C##Mes_profile?
alter user C##Mes profile C##Mes_profile; ----更改用户C##Mes的profile为C##Mes_profile
alter profile C##Mes_profile limit SESSIONS_PER_USER 20; ----限定用户C##Mes的连接数为2
select * from dba_profiles WHERE PROFILE LIKE '%C##MES_PROFIL%';

----先删除角色，然后创建新的角色
DROP ROLE C##ROLE_SELECT_BUSINESS;
CREATE ROLE C##ROLE_SELECT_BUSINESS;

---1.给他一些权限，包括连接权限，因为他要创建同义词，还需要给他同义词
grant connect,resource to C##ROLE_SELECT_BUSINESS;
grant create synonym to C##ROLE_SELECT_BUSINESS;
GRANT CREATE SESSION TO C##ROLE_SELECT_BUSINESS;  ----如果不赋予这个会如何？好像没事。

----赋予查询条件给他
--/*
--GRANT SELECT  ON WM_LOCATIONU TO C##ROLE_SELECT_BUSINESS; ----2021年2月3日09:21:22，单独的话，已经成功。
GRANT ALL  ON WM_PALLETU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_BILL_TYPEU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_PRODUCTU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_PRODUCT_UNITU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_TRANSFER_STATIONU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_CUSTOMERU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_UNITU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_PRODUCT_PATTERNU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_FACTURERU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_PRODUCT_BREEDU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_BRANDU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_ORGANIZATIONU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_EMPLOYEEU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_TEAMU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_TEAM_MEMBERU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_PALLET_TYPEU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_MATCH_PALLET_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_MATCH_PALLETU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_REGIONU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_SHELFU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_WAREHOUSEU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_STATIONU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_LOCATIONU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_PROFIT_LOSS_BILL_DETAIL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_PROFIT_LOSS_BILL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MOVE_BILL_DETAIL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MOVE_BILL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_OUT_BILL_ALLOT_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_PROFIT_LOSS_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MOVE_BILL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MOVE_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_IN_BILL_ALLOTU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_IN_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_IN_BILL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_OUT_BILL_ALLOTU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_OUT_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_OUT_BILL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MATCH_PALLET_PLAN_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_HANDOVER_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_SHIFTU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MANUAL_MATERIAL_BILL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MANUAL_MATERIAL_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MONTHLY_BALANCEU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MONTHLY_BALANCE_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_OUT_BILL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_OUT_BILL_DETAIL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MATCH_PALLET_PLANU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_PRODUCTION_PLAN_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_PRODUCTION_PLANU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_DAILY_BALANCE_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_INVENTORY_BILL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_INVENTORY_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_FORMULA_OUT_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_FORMULA_OUTU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_ASSORTED_BILL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_ASSORTED_BILLU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON BI_FORMULAU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_INVENTORY_BILL_DETAIL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_INVENTORY_BILL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_IN_BILL_ALLOT_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_IN_BILL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_IN_BILL_DETAIL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_DAILY_BALANCE_BILL_HISTORYU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINEU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_PALLETU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_PALLET_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_RETURNU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_HANDOVERU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_CALL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_PROFIT_LOSS_BILL_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_STORAGEU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_RETURN_DETAILU TO C##ROLE_SELECT_BUSINESS;
GRANT SELECT  ON WM_MACHINE_CALLU TO C##ROLE_SELECT_BUSINESS;

--*/
--GRANT DBA TO C##MES;  --不需要提交也能让C##MES有UNLIMITED TABLESPACE权限，即DBA角色权限
------回收权限
--REVOKE DBA FROM C##MES;
--REVOKE C##ROLE_SELECT_BUSINESS FROM C##MES;

----角色赋予用户
GRANT C##ROLE_SELECT_BUSINESS TO C##MES;
----create or replace SYNONYM WM_LOCATION FOR C##Fusion.WM_LOCATIONU; --在C##FUSION中执行这个达不到创建同名的效果。

--select * from user_sys_privs;

---->>>>>>>
----登录他的连接，并执行(拷贝过去执行即可，很快的）
/*
--create or replace SYNONYM  C##MES.WM_LOCATION FOR C##Fusion.WM_LOCATIONU;create or replace SYNONYM  C##MES.WM_PALLET FOR C##Fusion.WM_PALLETU;
create or replace SYNONYM  C##MES.WM_BILL_TYPE FOR C##Fusion.WM_BILL_TYPEU;
create or replace SYNONYM  C##MES.BI_PRODUCT FOR C##Fusion.BI_PRODUCTU;
create or replace SYNONYM  C##MES.BI_PRODUCT_UNIT FOR C##Fusion.BI_PRODUCT_UNITU;
create or replace SYNONYM  C##MES.BI_TRANSFER_STATION FOR C##Fusion.BI_TRANSFER_STATIONU;
create or replace SYNONYM  C##MES.BI_CUSTOMER FOR C##Fusion.BI_CUSTOMERU;
create or replace SYNONYM  C##MES.BI_UNIT FOR C##Fusion.BI_UNITU;
create or replace SYNONYM  C##MES.BI_PRODUCT_PATTERN FOR C##Fusion.BI_PRODUCT_PATTERNU;
create or replace SYNONYM  C##MES.BI_FACTURER FOR C##Fusion.BI_FACTURERU;
create or replace SYNONYM  C##MES.BI_PRODUCT_BREED FOR C##Fusion.BI_PRODUCT_BREEDU;
create or replace SYNONYM  C##MES.BI_BRAND FOR C##Fusion.BI_BRANDU;
create or replace SYNONYM  C##MES.BI_ORGANIZATION FOR C##Fusion.BI_ORGANIZATIONU;
create or replace SYNONYM  C##MES.BI_EMPLOYEE FOR C##Fusion.BI_EMPLOYEEU;
create or replace SYNONYM  C##MES.BI_TEAM FOR C##Fusion.BI_TEAMU;
create or replace SYNONYM  C##MES.BI_TEAM_MEMBER FOR C##Fusion.BI_TEAM_MEMBERU;
create or replace SYNONYM  C##MES.BI_PALLET_TYPE FOR C##Fusion.BI_PALLET_TYPEU;
create or replace SYNONYM  C##MES.BI_MATCH_PALLET_DETAIL FOR C##Fusion.BI_MATCH_PALLET_DETAILU;
create or replace SYNONYM  C##MES.BI_MATCH_PALLET FOR C##Fusion.BI_MATCH_PALLETU;
create or replace SYNONYM  C##MES.WM_REGION FOR C##Fusion.WM_REGIONU;
create or replace SYNONYM  C##MES.WM_SHELF FOR C##Fusion.WM_SHELFU;
create or replace SYNONYM  C##MES.WM_WAREHOUSE FOR C##Fusion.WM_WAREHOUSEU;
create or replace SYNONYM  C##MES.WM_STATION FOR C##Fusion.WM_STATIONU;
create or replace SYNONYM  C##MES.WM_LOCATION FOR C##Fusion.WM_LOCATIONU;
create or replace SYNONYM  C##MES.WM_PROFIT_LOSS_BILL_DETAIL_HISTORY FOR C##Fusion.WM_PROFIT_LOSS_BILL_DETAIL_HISTORYU;
create or replace SYNONYM  C##MES.WM_PROFIT_LOSS_BILL_HISTORY FOR C##Fusion.WM_PROFIT_LOSS_BILL_HISTORYU;
create or replace SYNONYM  C##MES.WM_MOVE_BILL_DETAIL_HISTORY FOR C##Fusion.WM_MOVE_BILL_DETAIL_HISTORYU;
create or replace SYNONYM  C##MES.WM_MOVE_BILL_HISTORY FOR C##Fusion.WM_MOVE_BILL_HISTORYU;
create or replace SYNONYM  C##MES.WM_OUT_BILL_ALLOT_HISTORY FOR C##Fusion.WM_OUT_BILL_ALLOT_HISTORYU;
create or replace SYNONYM  C##MES.WM_PROFIT_LOSS_BILL FOR C##Fusion.WM_PROFIT_LOSS_BILLU;
create or replace SYNONYM  C##MES.WM_MOVE_BILL_DETAIL FOR C##Fusion.WM_MOVE_BILL_DETAILU;
create or replace SYNONYM  C##MES.WM_MOVE_BILL FOR C##Fusion.WM_MOVE_BILLU;
create or replace SYNONYM  C##MES.WM_IN_BILL_ALLOT FOR C##Fusion.WM_IN_BILL_ALLOTU;
create or replace SYNONYM  C##MES.WM_IN_BILL FOR C##Fusion.WM_IN_BILLU;
create or replace SYNONYM  C##MES.WM_IN_BILL_DETAIL FOR C##Fusion.WM_IN_BILL_DETAILU;
create or replace SYNONYM  C##MES.WM_OUT_BILL_ALLOT FOR C##Fusion.WM_OUT_BILL_ALLOTU;
create or replace SYNONYM  C##MES.WM_OUT_BILL FOR C##Fusion.WM_OUT_BILLU;
create or replace SYNONYM  C##MES.WM_OUT_BILL_DETAIL FOR C##Fusion.WM_OUT_BILL_DETAILU;
create or replace SYNONYM  C##MES.WM_MATCH_PALLET_PLAN_DETAIL FOR C##Fusion.WM_MATCH_PALLET_PLAN_DETAILU;
create or replace SYNONYM  C##MES.WM_MACHINE_HANDOVER_DETAIL FOR C##Fusion.WM_MACHINE_HANDOVER_DETAILU;
create or replace SYNONYM  C##MES.BI_SHIFT FOR C##Fusion.BI_SHIFTU;
create or replace SYNONYM  C##MES.WM_MANUAL_MATERIAL_BILL_DETAIL FOR C##Fusion.WM_MANUAL_MATERIAL_BILL_DETAILU;
create or replace SYNONYM  C##MES.WM_MANUAL_MATERIAL_BILL FOR C##Fusion.WM_MANUAL_MATERIAL_BILLU;
create or replace SYNONYM  C##MES.WM_MONTHLY_BALANCE FOR C##Fusion.WM_MONTHLY_BALANCEU;
create or replace SYNONYM  C##MES.WM_MONTHLY_BALANCE_HISTORY FOR C##Fusion.WM_MONTHLY_BALANCE_HISTORYU;
create or replace SYNONYM  C##MES.WM_OUT_BILL_HISTORY FOR C##Fusion.WM_OUT_BILL_HISTORYU;
create or replace SYNONYM  C##MES.WM_OUT_BILL_DETAIL_HISTORY FOR C##Fusion.WM_OUT_BILL_DETAIL_HISTORYU;
create or replace SYNONYM  C##MES.WM_MATCH_PALLET_PLAN FOR C##Fusion.WM_MATCH_PALLET_PLANU;
create or replace SYNONYM  C##MES.WM_PRODUCTION_PLAN_DETAIL FOR C##Fusion.WM_PRODUCTION_PLAN_DETAILU;
create or replace SYNONYM  C##MES.WM_PRODUCTION_PLAN FOR C##Fusion.WM_PRODUCTION_PLANU;
create or replace SYNONYM  C##MES.WM_DAILY_BALANCE_BILL FOR C##Fusion.WM_DAILY_BALANCE_BILLU;
create or replace SYNONYM  C##MES.WM_INVENTORY_BILL_DETAIL FOR C##Fusion.WM_INVENTORY_BILL_DETAILU;
create or replace SYNONYM  C##MES.WM_INVENTORY_BILL FOR C##Fusion.WM_INVENTORY_BILLU;
create or replace SYNONYM  C##MES.WM_FORMULA_OUT_DETAIL FOR C##Fusion.WM_FORMULA_OUT_DETAILU;
create or replace SYNONYM  C##MES.WM_FORMULA_OUT FOR C##Fusion.WM_FORMULA_OUTU;
create or replace SYNONYM  C##MES.WM_ASSORTED_BILL_DETAIL FOR C##Fusion.WM_ASSORTED_BILL_DETAILU;
create or replace SYNONYM  C##MES.WM_ASSORTED_BILL FOR C##Fusion.WM_ASSORTED_BILLU;
create or replace SYNONYM  C##MES.BI_FORMULA FOR C##Fusion.BI_FORMULAU;
create or replace SYNONYM  C##MES.WM_INVENTORY_BILL_DETAIL_HISTORY FOR C##Fusion.WM_INVENTORY_BILL_DETAIL_HISTORYU;
create or replace SYNONYM  C##MES.WM_INVENTORY_BILL_HISTORY FOR C##Fusion.WM_INVENTORY_BILL_HISTORYU;
create or replace SYNONYM  C##MES.WM_IN_BILL_ALLOT_HISTORY FOR C##Fusion.WM_IN_BILL_ALLOT_HISTORYU;
create or replace SYNONYM  C##MES.WM_IN_BILL_HISTORY FOR C##Fusion.WM_IN_BILL_HISTORYU;
create or replace SYNONYM  C##MES.WM_IN_BILL_DETAIL_HISTORY FOR C##Fusion.WM_IN_BILL_DETAIL_HISTORYU;
create or replace SYNONYM  C##MES.WM_DAILY_BALANCE_BILL_HISTORY FOR C##Fusion.WM_DAILY_BALANCE_BILL_HISTORYU;
create or replace SYNONYM  C##MES.WM_MACHINE FOR C##Fusion.WM_MACHINEU;
create or replace SYNONYM  C##MES.WM_MACHINE_PALLET FOR C##Fusion.WM_MACHINE_PALLETU;
create or replace SYNONYM  C##MES.WM_MACHINE_PALLET_DETAIL FOR C##Fusion.WM_MACHINE_PALLET_DETAILU;
create or replace SYNONYM  C##MES.WM_MACHINE_RETURN FOR C##Fusion.WM_MACHINE_RETURNU;
create or replace SYNONYM  C##MES.WM_MACHINE_HANDOVER FOR C##Fusion.WM_MACHINE_HANDOVERU;
create or replace SYNONYM  C##MES.WM_MACHINE_CALL_DETAIL FOR C##Fusion.WM_MACHINE_CALL_DETAILU;
create or replace SYNONYM  C##MES.WM_PROFIT_LOSS_BILL_DETAIL FOR C##Fusion.WM_PROFIT_LOSS_BILL_DETAILU;
create or replace SYNONYM  C##MES.WM_STORAGE FOR C##Fusion.WM_STORAGEU;
create or replace SYNONYM  C##MES.WM_MACHINE_RETURN_DETAIL FOR C##Fusion.WM_MACHINE_RETURN_DETAILU;
create or replace SYNONYM  C##MES.WM_MACHINE_CALL FOR C##Fusion.WM_MACHINE_CALLU;
----*/