
create or replace function F_A1
return varchar2
is
    V_TEMP VARCHAR2(500); ----也可不定义变量
begin
  insert into C##FUSION.WM_REGIONU(WAREHOUSE_CODEU, REGION_CODEU, REGION_NAMEU, DISPLAY_ORDERU, REGION_TYPEU, ALLOT_IN_ORDERU, ALLOT_OUT_ORDERU, ACTIVEU, EXTERNAL_REGION_CODEU, REMARKU, CREATE_TIMEU, UPDATE_TIMEU, ROW_VERSIONU)
    values ( 'w002' ,  'w002r05' ,  '暂存区' ,  '5' ,  '3' ,  '0' ,  '0' ,  '1' ,  '' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
  insert into C##FUSION.WM_SHELFU(WAREHOUSE_CODEU, REGION_CODEU, SHELF_CODEU, SHELF_NAMEU, DISPLAY_ORDERU, ACTIVEU, REMARKU, CREATE_TIMEU, UPDATE_TIMEU, ROW_VERSIONU)
    values ( 'w002' ,  'w002r05' ,  'w002r05-shelf01' ,  '配盘货架01' ,  '1' ,  '1' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());

  FOR V_PANWEINUMBER IN 1 .. 29 LOOP
    dbms_output.put_line(lpad(V_PANWEINUMBER,2,'0'));
    insert into C##FUSION.WM_LOCATIONU(LOCATION_CODEU, LOCATION_NAMEU, LOCATION_TYPEU, WAREHOUSE_CODEU, REGION_CODEU, SHELF_CODEU, PRESET_PRODUCT_CODEU, PRESET_PRODUCT_NAMEU, IN_POSITION_NOU, OUT_POSITION_NOU, IN_WORK_EQUIPMENT_CODESU, OUT_WORK_EQUIPMENT_CODESU, PALLET_MAX_RESERVESU, MAX_PALLET_QUANTITYU, OUT_STRATEGYU, OUT_ALLOT_STRATEGYU, DISPLAY_ORDERU, ALLOT_IN_ORDERU, LOCATION_RFIDU, LOCATION_LAYERU, LOCATION_COLUMNU, COORDINATE_XU, COORDINATE_YU, LOCATION_STATUSU, FRONT_EQUIPMENT_CODESU, REAR_EQUIPMENT_CODESU, FRONT_POSITIONU, REAR_POSITIONU, LOCK_TAGU, REMARKU, CREATE_TIMEU, UPDATE_TIMEU, ROW_VERSIONU, EQUIPMENT_USEDU, POSITION_USEDU)
      values ( 'w002r05-0'|| lpad(V_PANWEINUMBER,2,'0') ,  '配盘货位'|| lpad(V_PANWEINUMBER,2,'0') ,  '0' ,  'w002' ,  'w002r05' ,  'w002r05-shelf01' ,  '' ,  '' ,  '0' ,  '0' ,  '' ,  '' ,  '200000' ,  '1' ,  '0' ,  '0' ,  '1' ,  '0' ,  '' ,  '1' ,  '1' ,  '0' ,  '0' ,  '1' ,  '' ,  '' ,  '0' ,  '0' ,  '' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID(), null,  '0' );

    insert into C##FUSION.WM_PALLETU(IDU, LOCATION_CODEU, PALLET_NAMEU, MATCH_PALLET_CODEU, MATCH_PALLET_NAMEU, UNIQUE_IDU, PRODUCT_COUNTU, STORAGE_QUANTITYU, IN_FROZEN_QUANTITYU, OUT_FROZEN_QUANTITYU, STORAGE_SEQUENCEU, PRODUCT_POSITIONU, BRAND_CODESU, BRAND_NAMESU, PALLET_TYPE_CODEU, PALLET_TYPE_NAMEU, PALLET_NOU, INBOUND_POSITION_NOU, OUTBOUND_POSITION_NOU, RESERVEU, CREATE_TIMEU, UPDATE_TIMEU, ROW_VERSIONU)
      values ( SYS_GUID(),  'w002r05-0'|| lpad(V_PANWEINUMBER,2,'0') ,  '盘位01' ,  '' ,  '' , null,  '0' ,  '0' ,  '0' ,  '0' ,  '0' , null,  '' ,  '' ,  '' ,  '' ,  '0' ,  '0' ,  '0' , null,  SYSDATE ,  SYSDATE ,  SYS_GUID());


  END LOOP;
  return '^_^';
  Exception when others then
    raise;
end;
/
set serveroutput on;
declare
  v_temp varchar2(50);
begin
  v_temp := F_A1();
  dbms_output.put_line(v_temp);
  commit;
  Exception when others then
    rollback;
    raise;
end;
/
drop function F_A1;