
delete from WM_PRODUCTION_PLANU;
delete from WM_PRODUCTION_PLAN_DETAILU;

commit;

insert into "C##FUSION"."WM_PRODUCTION_PLANU"("PRODUCTION_PLAN_NOU", "ORIGIN_PLAN_NOU", "PLAN_BEGIN_TIMEU", "PLAN_END_TIMEU", "MAKERU", "MAKE_TIMEU", "AUDITORU", "BILL_NOU", "AUDIT_TIMEU", "PRODUCTION_PLAN_STATUSU", "PRODUCTION_PLAN_ORIGINU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( 'P202004190002' , null,  SYSDATE ,  SYSDATE+1 ,  'admin' ,  SYSDATE ,  '' , null, null,  '0' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());

insert into "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU"("IDU", "PRODUCTION_PLAN_NOU", "SERIAL_NUMBERU", "TEAM_CODEU", "TEAM_NAMEU", "SHIFT_CODEU", "SHIFT_NAMEU", "MACHINE_CODEU", "MACHINE_NAMEU", "BRAND_CODEU", "BRAND_NAMEU", "ORIGIN_WORK_NOU", "PRODUCTION_PLAN_DETAIL_STATUSU", "PRODUCTION_BEGIN_TIMEU", "PRODUCTION_END_TIMEU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  'P202004190002' ,  '1' ,  '1' ,  '¼×°à' , null, null,  'Z304' ,  '4#×°·âÏä»ú' ,  '69010281666900001' ,  'ºìÆìÇþ£¨ÌìÐÐ½¡£©' , null,  '0' , null, null,  SYSDATE ,  SYSDATE ,  SYS_GUID());

update "C##FUSION"."WM_PRODUCTION_PLANU"
set "AUDITORU" =  'admin' , "AUDIT_TIMEU" =  SYSDATE , "PRODUCTION_PLAN_STATUSU" =  '1' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("PRODUCTION_PLAN_NOU" =  'P202004190002' ));

update "C##FUSION"."WM_PRODUCTION_PLANU"
set "PRODUCTION_PLAN_STATUSU" =  '2' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("PRODUCTION_PLAN_NOU" =  'P202004190002' ));



commit;


