
create or replace function F_01(
    IN_MATCH_PALLET_CODE varchar2
    ,IN_FACTURER_CODE varchar2
)
RETURN VARCHAR2
IS
    V_NUM_EX01 NUMBER;
    V_NUM_EX02 NUMBER;
    V_TEMP VARCHAR2(50);
    V_TEMP2 VARCHAR2(50);
    V_TEMP3 VARCHAR2(50);
    V_EXISTS_ROW NUMBER := 0;
BEGIN
  V_TEMP := '^_^';
  --V_NUM_EX01 := to_number(V_EX01);
  --V_NUM_EX02 := to_number(V_EX02);
  V_TEMP := 'I'|| TO_CHAR(SYSDATE, 'yymmddhh24miss');
  
  SELECT LOCATION_CODEU,IDU INTO V_TEMP, V_TEMP2 FROM WM_PALLETU WHERE LOCATION_CODEU IN (
    SELECT LOCATION_CODEU FROM(
      SELECT COUNT(LOCATION_CODEU) AS LNUM,LOCATION_CODEU  FROM WM_PALLETU WHERE LENGTH(LOCATION_CODEU)=8 GROUP BY LOCATION_CODEU ORDER BY LOCATION_CODEU ASC
      ) WHERE LNUM =1 AND STORAGE_QUANTITYU = 0
    ) AND MATCH_PALLET_CODEU IS NULL AND ROWNUM=1;
  dbms_output.put_line('插入了的货位是：'||V_TEMP||'   盘位ID:  '||V_TEMP2);
  dbms_output.put_line('对应的查询sql为：SELECT * FROM WM_STORAGEU  WHERE LOCATION_CODEU ='''||V_TEMP||''' AND PALLET_IDU='''||V_TEMP2||''';');
    
  ----插入盘位信息    
    update "C##FUSION"."WM_PALLETU" TB_PALLET
    set (IDU, LOCATION_CODEU, PALLET_NAMEU, MATCH_PALLET_CODEU, MATCH_PALLET_NAMEU, UNIQUE_IDU, PRODUCT_COUNTU
    , STORAGE_QUANTITYU, STORAGE_SEQUENCEU--, PRODUCT_POSITIONU
    ,BRAND_CODESU, BRAND_NAMESU, PALLET_TYPE_CODEU, PALLET_TYPE_NAMEU
    , CREATE_TIMEU, UPDATE_TIMEU) = (SELECT * FROM (  
      SELECT V_TEMP2 AS IDU, V_TEMP AS LOCATION_CODEU, '盘位' AS PALLET_NAMEU, TB_B.MATCH_PALLET_CODEU, TB_B.MATCH_PALLET_NAMEU, '99990001' AS UNIQUE_IDU
        , COUNT(*) OVER (PARTITION  by TB_A.MATCH_PALLET_CODEU) PRODUCT_COUNTU, SUM(TB_A.WAREHOUSE_QUANTITYU) OVER (PARTITION  by TB_A.MATCH_PALLET_CODEU) AS STORAGE_QUANTITYU
        , '1' AS STORAGE_SEQUENCEU--, '42401' AS PRODUCT_POSITIONU
        , TB_B.BRAND_CODESU AS BRAND_CODESU, TB_B.BRAND_NAMESU AS BRAND_NAMESU, TB_B.PALLET_TYPE_CODEU AS PALLET_TYPE_CODEU, TB_B.PALLET_TYPE_NAMEU AS PALLET_TYPE_NAMEU
        , sysdate AS CREATE_TIMEU, sysdate AS UPDATE_TIMEU
      FROM BI_MATCH_PALLET_DETAILU TB_A
      inner join BI_MATCH_PALLETU TB_B ON TB_B.MATCH_PALLET_CODEU = TB_A.MATCH_PALLET_CODEU WHERE TB_A.MATCH_PALLET_CODEU=IN_MATCH_PALLET_CODE ORDER BY TB_A.MATCH_PALLET_CODEU DESC
      ) WHERE ROWNUM=1)
    where (((TB_PALLET."IDU" =  V_TEMP2) --and (TB_PALLET."LOCATION_CODEU" = V_TEMP2 )
    ));
  ----插入库存信息
  INSERT INTO WM_STORAGEU (IDU, PALLET_IDU,  LOCATION_CODEU, PRODUCT_CODEU, PRODUCT_NAMEU, STORAGE_QUANTITYU, STORAGE_TIMEU, CREATE_TIMEU, UPDATE_TIMEU, ROW_VERSIONU, SAMPLINGU
      ,IN_FROZEN_QUANTITYU, OUT_FROZEN_QUANTITYU)
      SELECT SYS_GUID(), V_TEMP2 PALLET_IDU, V_TEMP LOCATION_CODEU, TB_A.PRODUCT_CODEU,TB_C.PRODUCT_NAMEU,TB_A.WAREHOUSE_QUANTITYU, SYSDATE AS STORAGE_TIMEU, SYSDATE CREATE_TIME
      , SYSDATE UPDATE_TIMEU, SYS_GUID() ROW_VERSIONU, '0', 0, 0
      FROM BI_MATCH_PALLET_DETAILU TB_A
      inner join BI_MATCH_PALLETU TB_B ON TB_B.MATCH_PALLET_CODEU = TB_A.MATCH_PALLET_CODEU 
      INNER JOIN BI_PRODUCTU TB_C ON TB_C.PRODUCT_CODEU = TB_A.PRODUCT_CODEU
      WHERE TB_A.MATCH_PALLET_CODEU=IN_MATCH_PALLET_CODE;
    
  ----更新库存的厂商信息
  SELECT COUNT(*) INTO V_EXISTS_ROW FROM BI_FACTURERU WHERE FACTURER_CODEU=IN_FACTURER_CODE;
  IF V_EXISTS_ROW >= 1 THEN
    UPDATE WM_STORAGEU SET (FACTURER_CODEU, FACTURER_NAMEU) = (SELECT FACTURER_CODEU, FACTURER_NAMEU FROM BI_FACTURERU WHERE FACTURER_CODEU=IN_FACTURER_CODE) 
      WHERE LOCATION_CODEU =V_TEMP AND PALLET_IDU=V_TEMP2;
  END IF;
  
  return '^_^';
END;
/
SET SERVEROUTPUT ON;
Declare
  ret varchar2(20);
Begin
  dbms_output.put_line('返回值：'||F_01('HJYYDH-1002NYSL', ''));
  --dbms_output.put_line('返回值：'||F_01('HQQMG-2002'));
  --dbms_output.put_line('返回值：'||F_01('HQQTXJ-2001'));
  --dbms_output.put_line('返回值：'||F_01('HQQMG-2002'));
  COMMIT WORK;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;