
--/*
CREATE OR REPLACE PROCEDURE p_location_SET_NORMAL_OTHERSBAD 
(V_LOCATION_CODEU01 VARCHAR2, V_LOCATION_CODEU02 VARCHAR2)
AS
BEGIN
----除设定的货位外，其他货位都改成不可用
  UPDATE WM_LOCATIONU SET LOCATION_STATUSU='0' WHERE LOCATION_CODEU NOT IN (V_LOCATION_CODEU01, V_LOCATION_CODEU02)--其他货位设定为不可用
    AND LENGTH(LOCATION_CODEU)=8;  --限定高架库
  UPDATE WM_LOCATIONU SET LOCATION_STATUSU='1' WHERE LOCATION_CODEU IN (V_LOCATION_CODEU01, V_LOCATION_CODEU02)
    AND LENGTH(LOCATION_CODEU)=8;  --限定高架库
END;
/
--/*
SET SERVEROUTPUT ON;
begin
  p_location_SET_NORMAL_OTHERSBAD(
    '2222'
    --, '01-01-04'
    , '03-15-01'
    --, '01-02-04'
  );
  commit;
end;
/