
-- 配置使得界面可以运行起来
SET DEFINE OFF;
update SYS_AREAU SET ACTIVEU=1 where NameU IN ('组盘管理','仓储管理','生产管理','仓储作业','数据监控','基础信息','系统管理');
select * from SYS_AREAU;
SET DEFINE OFF;
update SYS_MODULEU SET ACTIVEU=1;
update SYS_MODULEU SET ACTIVEU=0 where PARENT_IDU IS NULL AND NAMEU NOT IN ('组织机构管理','产品信息管理','生产基础信息','配盘管理','仓库基础信息','仓库单据管理','库存信息查询','历史单据查询','设备信息管理','路径信息管理','手工作业管理','自动作业管理','历史任务查询'
  ,'机组信息管理','生产计划管理','机组生产管理','设备基础信息','数据配置','在线监控','权限管理','系统设置','日志管理','工具','帮助');
select * from SYS_MODULEU;

-- 插入仓库和货架，好让程序能够一键初始化
SET DEFINE OFF;
Insert into C##FUSION.WM_WAREHOUSEU (WAREHOUSE_CODEU,WAREHOUSE_NAMEU,DISPLAY_ORDERU,WAREHOUSE_TYPEU,ACTIVEU,REMARKU,CREATE_TIMEU,UPDATE_TIMEU,ROW_VERSIONU) values ('w002','洛阳辅料库',1,0,1,null,to_date('12-10月-19','DD-MON-RR'),to_date('12-10月-19','DD-MON-RR'),'7787DC4E91C8334990C35DEA7F324616');
REM INSERTING into C##FUSION.WM_REGIONU
SET DEFINE OFF;
Insert into C##FUSION.WM_REGIONU (WAREHOUSE_CODEU,REGION_CODEU,REGION_NAMEU,DISPLAY_ORDERU,REGION_TYPEU,ALLOT_IN_ORDERU,ALLOT_OUT_ORDERU,ACTIVEU,EXTERNAL_REGION_CODEU,REMARKU,CREATE_TIMEU,UPDATE_TIMEU,ROW_VERSIONU) values ('w002','w002r01','洛阳辅料库区',1,0,0,0,1,null,null,to_date('12-10月-19','DD-MON-RR'),to_date('12-10月-19','DD-MON-RR'),'95B23C4E90C67640B8111BD213381099');


-- 插入一键配置的行列
SET DEFINE OFF;
Insert into C##FUSION.SYS_DBINITIALIZEU (IDU,INITIALIZE_NAMEU,CREATE_TIMEU,UPDATE_TIMEU,ROW_VERSIONU) values ('F528E0C4BCC8834EB9546579CB5D7CE4','LYYC_FLK',sysdate,sysdate,'7967E6EAD7D86443A70C795F56F0AB6A');
INSERT INTO C##FUSION.SYS_WAREHOUSE_CONFIGU (IDU, DBINITIALIZ_IDU, WAREHOUSE_CONFIG_NAMEU, GENERATE_ORDERU, WAREHOUSE_CODEU, REGION_CODEU, SHELF_CODE_FORMATU, SHELF_LAYER_COUNTU, SHELF_COLUMN_COUNTU, SHELF_ROW_COUNTU, SHELF_LAYER_CODE_WIDTHU, SHELF_COLUMN_CODE_WIDTHU, SHELF_ROW_CODE_WIDTHU, SHELF_LAYER_STARTU, SHELF_COLUMN_STARTU, SHELF_ROW_STARTU, LOCATION_CODE_FORMATU, LOCATION_NAME_FORMATU, WORK_POSITION_NO_FORMATU, WORK_POSITION_NAME_FORMATU, WORK_REGION_CODE_FORMATU, WORK_REGION_NAME_FORMATU, WORK_REGION_COUNTU, WORK_REGION_STARTU, WORK_EQUIPMENT_CODE_FORMATU, WORK_EQUIPMENT_NAME_FORMATU, WORK_EQUIPMENT_COUNTU, WORK_EQUIPMENT_STARTU, EQUIPMENT_CONTROL_SHELFT_ROW_COUNTU, ACTIVEU, IS_GENERATE_WORK_POSITIONU, EQUIPMENT_IS_REVERSE_CONTROL_SHELFU, CREATE_TIMEU, UPDATE_TIMEU, ROW_VERSIONU) 
    VALUES (SYS_GUID(), 'F528E0C4BCC8834EB9546579CB5D7CE4', '仓库配置001', 1, 'w002', 'w002r01', 'w002r01-{0}', 4, 32, 4, 2, 2, 2, 1, 1, 1
    , '{1}-{2}-{0}', '{1}排-{2}列-{0}层', '{1}{2}{0}', '{1}排{2}列{0}层', UPPER('r-CR{0}'), '{0}号堆垛机区', 2, 1, UPPER('cr{0}'), UPPER('{0}号堆垛机'),2, 1, 2, 1, 1, 0, sysdate, sysdate, SYS_GUID()); 


COMMIT WORK;