

-----#####禁用约束，约束名可从“各种有用的容易使用到的.sql文件”查找
/*
UPDATE WM_STORAGEU SET PRODUCT_CODEU='TEST_TEST' WHERE PRODUCT_CODEU='P0003'; ----只能更新主键引用表，被引用表的CODE不能更改
SELECT * FROM  C##FUSION.WM_PALLETU;
----新箱皮要改成 箱皮(芒果) 箱皮(新版银河) 箱皮(天行健)
SELECT * FROM WM_STORAGEU TB_A inner join WM_PALLETU TB_B ON TB_B.IDU= TB_A.PALLET_IDU WHERE PRODUCT_CODEU = '03140100000000248';
SELECT * FROM TM_TASK_DETAILU WHERE PRODUCT_CODEU='03140100000000248';
----查找库存中还没使用的产品编码
SELECT * FROM BI_PRODUCTU TB_A
  LEFT JOIN WM_STORAGEU TB_B ON TB_B.PRODUCT_CODEU = TB_A.PRODUCT_CODEU
  WHERE TB_B.PRODUCT_CODEU IS NULL;
--*/
  
  
--/*可以的话，先清除关联到产品编码的Task、Machine_pallet_detail、Machine_return、Machine_Handover等等
--*/
----根据WM_PALLETU的BRAND_CODESU更改纸箱的类别
--SELECT * FROM WM_PALLETU WHERE MATCH_PALLET_CODEU IN ('HQQMG-2001', 'HQQXBYH-2001', 'HQQTXJ-2001');
--SELECT * FROM BI_MATCH_PALLET_DETAILU WHERE MATCH_PALLET_CODEU='HQQMG-2001';

create or replace function F_A1
return varchar2
is
  V_A VARCHAR2(100);
  V_B VARCHAR2(100);
begin
----1）在网页上手动删除更快，先删除除03140100000000248 硬盒简化循环烟箱 这个之外的那三个新箱皮，都改成MES提供的新箱皮编码
----2）添加这三个产品编码以及其产品单位

insert into "C##FUSION"."BI_PRODUCTU"("PRODUCT_CODEU", "PRODUCT_NAMEU", "PRODUCT_NOU", "FULL_PHONETICIZEU", "SHORT_PHONETICIZEU", "DISPLAY_ORDERU", "UNIFORM_CODEU", "FACTURER_CODEU", "CARGO_OWNER_CODEU", "ABNORMITYU", "LENGTHU", "WIDTHU", "HEIGHTU", "ACTIVEU", "IS_BIG_PRODUCTU", "SORT_NOU", "REMARKU", "PRODUCT_CATEGORY_CODEU", "PRODUCT_BREED_CODEU", "PRODUCT_PATTERN_CODEU", "PRODUCT_GRADE_CODEU", "PRODUCT_ORIGIN_CODEU", "YEARU", "WEIGHTU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( 'HQQMGSCYX' ,  '硬盒简化循环烟箱（芒果）' ,  '0' ,  'YingHeJianHuaXunHuanYanXiangMangGuo' ,  'YHJHXHYXMG' ,  '0' ,  '' ,  '' , null,  '0' ,  '0' ,  '0' ,  '0' ,  '1' ,  '0' ,  '0' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());

insert into "C##FUSION"."BI_PRODUCTU"("PRODUCT_CODEU", "PRODUCT_NAMEU", "PRODUCT_NOU", "FULL_PHONETICIZEU", "SHORT_PHONETICIZEU", "DISPLAY_ORDERU", "UNIFORM_CODEU", "FACTURER_CODEU", "CARGO_OWNER_CODEU", "ABNORMITYU", "LENGTHU", "WIDTHU", "HEIGHTU", "ACTIVEU", "IS_BIG_PRODUCTU", "SORT_NOU", "REMARKU", "PRODUCT_CATEGORY_CODEU", "PRODUCT_BREED_CODEU", "PRODUCT_PATTERN_CODEU", "PRODUCT_GRADE_CODEU", "PRODUCT_ORIGIN_CODEU", "YEARU", "WEIGHTU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '150600002049' ,  '硬盒简化循环烟箱（新版银河）' ,  '0' ,  'YingHeJianHuaXunHuanYanXiangXinBanYinHe' ,  'YHJHXHYXXBYH' ,  '0' ,  '' ,  '' , null,  '0' ,  '0' ,  '0' ,  '0' ,  '1' ,  '0' ,  '0' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());

insert into "C##FUSION"."BI_PRODUCTU"("PRODUCT_CODEU", "PRODUCT_NAMEU", "PRODUCT_NOU", "FULL_PHONETICIZEU", "SHORT_PHONETICIZEU", "DISPLAY_ORDERU", "UNIFORM_CODEU", "FACTURER_CODEU", "CARGO_OWNER_CODEU", "ABNORMITYU", "LENGTHU", "WIDTHU", "HEIGHTU", "ACTIVEU", "IS_BIG_PRODUCTU", "SORT_NOU", "REMARKU", "PRODUCT_CATEGORY_CODEU", "PRODUCT_BREED_CODEU", "PRODUCT_PATTERN_CODEU", "PRODUCT_GRADE_CODEU", "PRODUCT_ORIGIN_CODEU", "YEARU", "WEIGHTU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '03140100100000195' ,  '硬盒简化循环烟箱（天行健）' ,  '0' ,  'YingHeJianHuaXunHuanYanXiangTianXingJian' ,  'YHJHXHYXTXJ' ,  '0' ,  '' ,  '' , null,  '0' ,  '0' ,  '0' ,  '0' ,  '1' ,  '0' ,  '0' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());


insert into "C##FUSION"."BI_PRODUCT_UNITU"("IDU", "PRODUCT_CODEU", "UNIT_CODEU", "UNIT_NAMEU", "UNIT_TYPEU", "TRANSFER_RATEU", "ACTIVEU", "DEFAULT_UNITU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  '03140100100000195' ,  '902' ,  '个' ,  '1' ,  '1' ,  '1' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_PRODUCT_UNITU"("IDU", "PRODUCT_CODEU", "UNIT_CODEU", "UNIT_NAMEU", "UNIT_TYPEU", "TRANSFER_RATEU", "ACTIVEU", "DEFAULT_UNITU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  '03140100100000195' ,  '902' ,  '个' ,  '2' ,  '1' ,  '1' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
update "C##FUSION"."BI_PRODUCT_UNITU"
set "DEFAULT_UNITU" =  '1' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (( ("PRODUCT_CODEU" =  '03140100100000195' )) AND "UNIT_TYPE"=1);

insert into "C##FUSION"."BI_PRODUCT_UNITU"("IDU", "PRODUCT_CODEU", "UNIT_CODEU", "UNIT_NAMEU", "UNIT_TYPEU", "TRANSFER_RATEU", "ACTIVEU", "DEFAULT_UNITU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  '150600002049' ,  '902' ,  '个' ,  '1' ,  '1' ,  '1' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_PRODUCT_UNITU"("IDU", "PRODUCT_CODEU", "UNIT_CODEU", "UNIT_NAMEU", "UNIT_TYPEU", "TRANSFER_RATEU", "ACTIVEU", "DEFAULT_UNITU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  '150600002049' ,  '902' ,  '个' ,  '2' ,  '1' ,  '1' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
update "C##FUSION"."BI_PRODUCT_UNITU"
set "DEFAULT_UNITU" =  '1' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (( ("PRODUCT_CODEU" =  '150600002049' )) AND "UNIT_TYPE"=1);

insert into "C##FUSION"."BI_PRODUCT_UNITU"("IDU", "PRODUCT_CODEU", "UNIT_CODEU", "UNIT_NAMEU", "UNIT_TYPEU", "TRANSFER_RATEU", "ACTIVEU", "DEFAULT_UNITU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  'HQQMGSCYX' ,  '902' ,  '个' ,  '1' ,  '1' ,  '1' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_PRODUCT_UNITU"("IDU", "PRODUCT_CODEU", "UNIT_CODEU", "UNIT_NAMEU", "UNIT_TYPEU", "TRANSFER_RATEU", "ACTIVEU", "DEFAULT_UNITU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  'HQQMGSCYX' ,  '902' ,  '个' ,  '2' ,  '1' ,  '1' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
update "C##FUSION"."BI_PRODUCT_UNITU"
set "DEFAULT_UNITU" =  '1' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (( ("PRODUCT_CODEU" =  'HQQMGSCYX' )) AND "UNIT_TYPE"=1);

----3）03140100000000248 存在于配盘 HQQMG-2001 HQQXBYH-2001 HQQTXJ-2001

  V_A := 'HQQMGSCYX';
  V_B := 'HQQMG-2001';
  UPDATE BI_MATCH_PALLET_DETAILU SET PRODUCT_CODEU=V_A WHERE MATCH_PALLET_CODEU=V_B;
  UPDATE WM_STORAGEU TB_A SET PRODUCT_CODEU= V_A,PRODUCT_NAMEU=PRODUCT_NAMEU||'（芒果）' WHERE PALLET_IDU IN (SELECT IDU FROM WM_PALLETU WHERE MATCH_PALLET_CODEU=V_B);
  V_A := '150600002049';
  V_B := 'HQQXBYH-2001';
  UPDATE BI_MATCH_PALLET_DETAILU SET PRODUCT_CODEU=V_A WHERE MATCH_PALLET_CODEU=V_B;
  UPDATE WM_STORAGEU TB_A SET PRODUCT_CODEU= V_A,PRODUCT_NAMEU=PRODUCT_NAMEU||'（新版银河）' WHERE PALLET_IDU IN (SELECT IDU FROM WM_PALLETU WHERE MATCH_PALLET_CODEU=V_B);
  V_A := '03140100100000195';
  V_B := 'HQQTXJ-2001';
  UPDATE BI_MATCH_PALLET_DETAILU SET PRODUCT_CODEU=V_A WHERE MATCH_PALLET_CODEU=V_B;
  UPDATE WM_STORAGEU TB_A SET PRODUCT_CODEU= V_A,PRODUCT_NAMEU=PRODUCT_NAMEU||'（天行健）' WHERE PALLET_IDU IN (SELECT IDU FROM WM_PALLETU WHERE MATCH_PALLET_CODEU=V_B);
  ----连BI_PRODUCTU也要更改
  V_A := '03050101000000009';
  V_B := 'P0004';
  UPDATE BI_MATCH_PALLET_DETAILU SET PRODUCT_CODEU=V_A WHERE PRODUCT_CODEU=V_B;
  UPDATE WM_STORAGEU TB_A SET PRODUCT_CODEU= V_A,TB_A.PRODUCT_NAMEU='26.5mm*32g/m2A60CU木浆竖纹卷烟纸' WHERE PRODUCT_CODEU=V_B;
  DELETE FROM BI_PRODUCTU WHERE PRODUCT_CODEU='P0004';
  DELETE FROM BI_PRODUCT_UNITU WHERE PRODUCT_CODEU='P0004';
  ----连BI_PRODUCTU也要更改
  V_A := '150600002049';
  V_B := 'P0003';
  UPDATE BI_MATCH_PALLET_DETAILU SET PRODUCT_CODEU=V_A WHERE PRODUCT_CODEU=V_B;
  UPDATE WM_STORAGEU TB_A SET PRODUCT_CODEU= V_A WHERE PRODUCT_CODEU=V_B;
  UPDATE BI_PRODUCTU SET PRODUCT_CODEU= V_A WHERE PRODUCT_CODEU=V_B;
  ----连BI_PRODUCTU也要更改
  V_A := '03060200000000071';
  V_B := 'P0002';
  UPDATE BI_MATCH_PALLET_DETAILU SET PRODUCT_CODEU=V_A WHERE PRODUCT_CODEU=V_B;
  UPDATE WM_STORAGEU TB_A SET PRODUCT_CODEU= V_A WHERE PRODUCT_CODEU=V_B;
  DELETE FROM BI_PRODUCTU  WHERE PRODUCT_CODEU='03060200000000071';
  DELETE FROM BI_PRODUCT_UNITU WHERE PRODUCT_CODEU='03060200000000071';
  UPDATE BI_PRODUCTU SET PRODUCT_CODEU= V_A WHERE PRODUCT_CODEU=V_B;
  UPDATE BI_PRODUCT_UNITU SET PRODUCT_CODEU = V_A WHERE  PRODUCT_CODEU=V_B;

  DELETE FROM BI_PRODUCTU WHERE PRODUCT_CODEU='03140100000000248';
  DELETE FROM BI_PRODUCT_UNITU WHERE PRODUCT_CODEU='03140100000000248';/**/
  return '^_^';
  Exception when others then
    raise;
end;
/
alter table BI_PRODUCT_UNITU disable constraint FK_BI_PRODUCT_UNITU_1434066075;
/
set serveroutput on;
declare
  v_temp varchar2(50);
begin
  v_temp := F_A1();
  dbms_output.put_line(v_temp);
  --rollback;
  commit;
  Exception when others then
    rollback;
    raise;
end;
/
drop function F_A1;
alter table BI_PRODUCT_UNITU ENABLE constraint FK_BI_PRODUCT_UNITU_1434066075;
/


