


----////查询表中某字段不一样的所有唯一记录
--SELECT TB_B.TRANSFER_BILL_NOU, COUNT(TB_B.TRANSFER_BILL_NOU)
SELECT * FROM WM_MACHINE_HANDOVER_DETAILU TB_B WHERE TB_B.IDU IN (
SELECT IDU FROM (
SELECT TB_A.IDU, TRANSFER_BILL_NOU, row_number() over (PARTITION BY TB_A.TRANSFER_BILL_NOU ORDER BY TRANSFER_BILL_NOU DESC)  V_ROWNUM FROM WM_MACHINE_HANDOVER_DETAILU TB_A WHERE TRANSFER_QUANTITYU=0 --IDU是表中唯一的
) WHERE V_ROWNUM = 1); --GROUP BY TB_B.TRANSFER_BILL_NOU;
/*
update WM_MACHINE_HANDOVER_DETAILU TB_B set TB_B.TRANSFER_QUANTITYU=TB_B.TRANSFER_RATEU, TB_B.RECEIVE_QUANTITYU = TB_B.TRANSFER_RATEU WHERE TB_B.IDU IN (
SELECT IDU FROM (
SELECT TB_A.IDU, TRANSFER_BILL_NOU, row_number() over (PARTITION BY TB_A.TRANSFER_BILL_NOU ORDER BY TRANSFER_BILL_NOU DESC)  V_ROWNUM FROM WM_MACHINE_HANDOVER_DETAILU TB_A WHERE TRANSFER_QUANTITYU=0 --IDU是表中唯一的
) WHERE V_ROWNUM = 1); --GROUP BY TB_B.TRANSFER_BILL_NOU;
--*/

----更新后，通过以下语句查找
SELECT * FROM WM_MACHINE_HANDOVER_DETAILU TB_B WHERE TB_B.TRANSFER_BILL_NOU IN (
SELECT TRANSFER_BILL_NOU FROM (
SELECT TB_A.IDU, TRANSFER_BILL_NOU, row_number() over (PARTITION BY TB_A.TRANSFER_BILL_NOU ORDER BY TRANSFER_BILL_NOU DESC)  V_ROWNUM FROM WM_MACHINE_HANDOVER_DETAILU TB_A WHERE TRANSFER_QUANTITYU=0 --IDU是表中唯一的
)); --GROUP BY TB_B.TRANSFER_BILL_NOU;


----最后，删除，移交时为0的细表
delete FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_QUANTITYU=0;


----移交单号：T202005060029所对应货位：108002中的产品：120mm*21μm BOPP高收缩膜在要料呼叫记录或者移交单接收中不存在，请检查！ 生产计划单号：P202005060002
SELECT * FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_BILL_NOU='T202005060029' AND SOURCE_LOCATION_CODEU='108002' AND PRODUCT_NAMEU='120mm*21μm BOPP高收缩膜';
----SOL
DELETE FROM WM_MACHINE_HANDOVER_DETAILU WHERE IDU='8A9D8E06B5A6F14995FBC743EE73C61F';
----移交单号：T202005060026 所对应货位：108004中的产品：红旗渠（芒果）68mm烫印接装纸在要料呼叫记录或者移交单接收中不存在，请检查！ P202005060003
DELETE FROM WM_MACHINE_HANDOVER_DETAILU WHERE IDU='70CAD920B2F8564C9A267D9738F37744';

SELECT * FROM WM_MACHINE_HANDOVERU WHERE TRANSFER_BILL_NOU IN (
SELECT TRANSFER_BILL_NOU FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_BILL_NOU='T202005060029' AND SOURCE_LOCATION_CODEU='108002' AND PRODUCT_NAMEU='120mm*21μm BOPP高收缩膜'
);

SELECT * FROM WM_MACHINE_CALLU WHERE IDU IN (
  SELECT MACHINE_CALL_IDU FROM WM_MACHINE_CALL_DETAILU WHERE MACHINE_CALL_IDU IN (SELECT IDU FROM WM_MACHINE_CALLU WHERE MACHINE_CODEU='B208' AND PALLET_POSITIONU='2') AND PRODUCT_NAMEU='120mm*21μm BOPP高收缩膜'
)  ORDER BY CREATE_TIMEU;
SELECT * FROM WM_MACHINE_CALL_DETAILU WHERE MACHINE_CALL_IDU IN (SELECT IDU FROM WM_MACHINE_CALLU WHERE MACHINE_CODEU='B208' AND PALLET_POSITIONU='2') AND PRODUCT_NAMEU='120mm*21μm BOPP高收缩膜' ORDER BY CREATE_TIMEU;
SELECT * FROM WM_MACHINE_CALL_DETAILU WHERE MACHINE_CALL_IDU IN (SELECT IDU FROM WM_MACHINE_CALLU WHERE PRODUCTION_PLAN_NOU='P202005060002');