

UPDATE WM_MACHINE_HANDOVER_DETAILU SET TRANSFER_QUANTITYU=TRANSFER_RATEU, RECEIVE_QUANTITYU=TRANSFER_RATEU WHERE IDU IN (
SELECT IDU FROM (
SELECT DISTINCT(TRANSFER_BILL_NOU), IDU, TRANSFER_QUANTITYU FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_QUANTITYU=0 ORDER BY CREATE_TIMEU DESC)); --IDU是表中唯一的

SELECT * FROM WM_MACHINE_HANDOVER_DETAILU WHERE IDU IN (
SELECT IDU FROM (
SELECT DISTINCT(TRANSFER_BILL_NOU), IDU, TRANSFER_QUANTITYU FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_QUANTITYU=0 ORDER BY CREATE_TIMEU DESC)); --IDU是表中唯一的

DELETE FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_QUANTITYU=0;



SELECT * FROM WM_MACHINE_RETURN_DETAILU WHERE RETURN_BILL_NOU='M202005080001';



SELECT * FROM WM_MACHINE_CALLU;
select * from WM_MACHINE_CALL_DETAILU WHERE MACHINE_CALL_IDU IN
(
SELECT IDU FROM WM_MACHINE_CALLU WHERE CREATE_TIMEU < (SELECT CREATE_TIMEU FROM WM_MACHINE_RETURN_DETAILU WHERE IDU='FAD9B2C43C678B40B15430B77DA75C0B') AND MACHINE_CODEU='J102');

SELECT * FROM WM_MACHINE_RETURNU WHERE RETURN_BILL_NOU='M202005080001';


SELECT * FROM WM_MACHINE_HANDOVER_DETAILU WHERE IDU IN (
SELECT IDU FROM WM_MACHINE_HANDOVER_DETAILU WHERE TRANSFER_QUANTITYU=0 GROUP BY TRANSFER_BILL_NOU) ORDER BY TRANSFER_BILL_NOU;
