


SELECT * FROM  C##FUSION.WM_PALLETU;
----新箱皮要改成 箱皮(芒果) 箱皮(新版银河) 箱皮(天行健)
SELECT * FROM WM_STORAGEU TB_A inner join WM_PALLETU TB_B ON TB_B.IDU= TB_A.PALLET_IDU WHERE PRODUCT_CODEU = '03140100000000248';
SELECT * FROM TM_TASK_DETAILU WHERE PRODUCT_CODEU='03140100000000248';
----查找库存中还没使用的产品编码
SELECT * FROM BI_PRODUCTU TB_A
  LEFT JOIN WM_STORAGEU TB_B ON TB_B.PRODUCT_CODEU = TB_A.PRODUCT_CODEU
  WHERE TB_B.PRODUCT_CODEU IS NULL;