--将作业位置和名称修改成与pallet_positionu一致
--把那些要改数据依据的标志位找出来，只有2,4，6,8机组的编号要改
SELECT PALLET_POSITIONU, WORK_POSITION_NOU, WORK_POSITION_NAMEU FROM WM_MACHINE_PALLETU WHERE MACHINE_CODEU = 'J1'||LPAD('2',2,'0') OR MACHINE_CODEU='B2' || LPAD('2',2,'0')
  ORDER BY WORK_POSITION_NOU;
--更新wm_machince_palletu的work_position_no；Name就不要改了，这是机器最终送到的位置，AGV也只认这个编号，这个不能改
--UPDATE WM_MACHINE_PALLETU SET WORK_POSITION_NOU='[NEW WORK_POSITION_NOU]'
-- WHERE MACHINE_CODEU = 'J1'||LPAD('2',2,'0') OR MACHINE_CODEU='B2' || LPAD('2',2,'0') ;
--依据相应内容更新TM_work_positionu
--UPDATE TM_WORK_POSITIONU SET WORK_POSITIONU='[NEW WORK_POSITION_NOU]' WHERE WORK_POSITION_NAMEU=[WORK_POSITION_NAMEU]' AND WORK_POSITION_NOU='WORK_POSITION_NOU';
