/*
SELECT * FROM WM_PALLETU WHERE LOCATION_CODEU = '01-32-01';
SELECT * FROM WM_STORAGEU;
--*/
----清空任务数据
DELETE FROM TM_TASK_DETAILU;
delete from TM_TASKU;
delete from TM_TASK_HISTORYU;
----清空出库单、入库单
DELETE FROM WM_IN_BILL_ALLOTU;
DELETE FROM WM_IN_BILL_DETAILU;
DELETE FROM WM_IN_BILLU;
DELETE FROM WM_OUT_BILL_ALLOTU;
DELETE FROM WM_OUT_BILL_DETAILU;
DELETE FROM WM_OUT_BILLU;
----删除交互信息
DELETE FROM DMT_INTERACTIVE_DATAU;
DELETE FROM DMT_INTERACTIVE_MANAGEU;
DELETE FROM DMT_INTERACTIVE_MESSAGEU;
DELETE FROM EM_EQUIPMENT_TASKU; 
commit;