
--/*
------删除机组作业影响到的查询表
--删除机组呼叫信息
DELETE FROM WM_MACHINE_CALLU;
DELETE FROM WM_MACHINE_CALL_DETAILU;
--*/
--/*
--删除机组移交记录
DELETE FROM WM_MACHINE_HANDOVER_DETAILU;
DELETE FROM WM_MACHINE_HANDOVERU;
--删除机组余料返库信息
DELETE FROM WM_MACHINE_RETURNU;
DELETE FROM WM_MACHINE_RETURN_DETAILU;
--删除生产计划
DELETE FROM "C##FUSION"."WM_PRODUCTION_PLANU";
DELETE FROM "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU";
--*/
/*
--删除移库单据
DELETE  FROM WM_MOVE_BILL_DETAILU;
DELETE  FROM WM_MOVE_BILLU;
--删除任务
DELETE FROM TM_TASKU;
DELETE FROM TM_TASK_DETAILU;
------删除入库单据
----DELETE FROM WM_IN_BILL_ALLOT_HISTORYU;
----DELETE FROM WM_IN_BILL_ALLOTU;
----DELETE FROM WM_IN_BILL_DETAILU;
----DELETE FROM WM_IN_BILL_HISTORYU;
----DELETE FROM WM_IN_BILLU;
------删除拼盘入库单据
----DELETE FROM WM_ASSORTED_BILL_DETAILU;
----DELETE FROM WM_ASSORTED_BILLU;
--删除出库单据
DELETE FROM WM_OUT_BILL_ALLOT_HISTORYU;
DELETE FROM WM_OUT_BILL_ALLOTU;
DELETE FROM WM_OUT_BILL_DETAIL_HISTORYU;
DELETE FROM WM_OUT_BILL_DETAILU;
DELETE FROM WM_OUT_BILL_HISTORYU;
DELETE FROM WM_OUT_BILLU;
--*/

----更新所有生产计划状态为已结单
UPDATE WM_PRODUCTION_PLANU SET PRODUCTION_PLAN_STATUSU=3 WHERE PRODUCTION_PLAN_STATUSU=2;
----测试的时候该直接清空信息
DELETE FROM WM_PRODUCTION_PLANU;
--删除机组下盘位细表
DELETE FROM WM_MACHINE_PALLET_DETAILU;
----更新所有机组中的盘位为空闲
update "C##FUSION"."WM_MACHINE_PALLETU"
set "CURRENT_BRAND_CODEU" =  '' , "CURRENT_BRAND_NAMEU" =  '' 
    , "CURRENT_MATCH_PALLET_CODEU" =  '' , "CURRENT_MATCH_PALLET_NAMEU" =  '' , "CURRENT_UNIQUE_IDU" =  '' , "MACHINE_PALLET_STATUSU" =  '0' 
    , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID();
update TM_WORK_POSITIONU SET USED_QUANTITYU=0 WHERE LENGTH( WORK_POSITION_NOU)=6;
----清空库存pallet信息，对应点：长度为6
UPDATE WM_PALLETU SET MATCH_PALLET_CODEU='', MATCH_PALLET_NAMEU='',UNIQUE_IDU='',PRODUCT_COUNTU=0,STORAGE_QUANTITYU=0,IN_FROZEN_QUANTITYU=0,OUT_FROZEN_QUANTITYU=0
    ,PRODUCT_POSITIONU='',BRAND_CODESU='',BRAND_NAMESU='',PALLET_TYPE_CODEU='',PALLET_TYPE_NAMEU='' WHERE LENGTH(LOCATION_CODEU)=6;
--删除机组中的库存Storage信息
DELETE FROM WM_STORAGEU WHERE LENGTH(LOCATION_CODEU)=6;
--更改所有机组的已缓存量和已使用量
update "C##FUSION"."TM_WORK_POSITIONU"
set "CACHED_QUANTITYU" =  '0' , "USED_QUANTITYU" =  '0' , "REMARKU" =  '' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (LENGTH("WORK_POSITION_NOU")=6);

COMMIT;
