/*
----更新班组信息
insert into "C##FUSION"."BI_TEAMU"("TEAM_CODEU", "TEAM_NAMEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '1' ,  '甲班' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_TEAMU"("TEAM_CODEU", "TEAM_NAMEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '2' ,  '乙班' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_TEAMU"("TEAM_CODEU", "TEAM_NAMEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '3' ,  '丙班' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
update "C##FUSION"."SYS_SEQUENCEU"
set "PREFIXU" =  '' , "SUFFIXU" =  '' , "SERIAL_NUMBER_LENGTHU" =  '1' , "GROUP_NAMEU" =  '',"CURRENT_NUMERICU" =  '4'  , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("IDU" =  SYS_GUID()));

----将原先班组的信息更新过来
insert into "C##FUSION"."BI_TEAM_MEMBERU"("IDU", "TEAM_CODEU", "EMPLOYEE_CODEU", "TEAM_LEADERU", "CREATE_TIMEU", "ROW_VERSIONU")
    SELECT SYS_GUID(), '1', "EMPLOYEE_CODEU", "TEAM_LEADERU", SYSDATE, SYS_GUID() FROM BI_TEAM_MEMBERU WHERE TEAM_CODEU IN ('T0001');
insert into "C##FUSION"."BI_TEAM_MEMBERU"("IDU", "TEAM_CODEU", "EMPLOYEE_CODEU", "TEAM_LEADERU", "CREATE_TIMEU", "ROW_VERSIONU")
    SELECT SYS_GUID(), '2', "EMPLOYEE_CODEU", "TEAM_LEADERU", SYSDATE, SYS_GUID() FROM BI_TEAM_MEMBERU WHERE TEAM_CODEU IN ('T0002');
insert into "C##FUSION"."BI_TEAM_MEMBERU"("IDU", "TEAM_CODEU", "EMPLOYEE_CODEU", "TEAM_LEADERU", "CREATE_TIMEU", "ROW_VERSIONU")
    SELECT SYS_GUID(), '3', "EMPLOYEE_CODEU", "TEAM_LEADERU", SYSDATE, SYS_GUID() FROM BI_TEAM_MEMBERU WHERE TEAM_CODEU IN ('T0003');
    
----插入新的牌号信息，添加MES那方的牌号信息
insert into "C##FUSION"."BI_BRANDU"("BRAND_CODEU", "BRAND_NAMEU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '69010281666900001' ,  '红旗渠（天行健）' ,  '1' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_BRANDU"("BRAND_CODEU", "BRAND_NAMEU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '69010281617180001' ,  '红旗渠(芒果)' ,  '1' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_BRANDU"("BRAND_CODEU", "BRAND_NAMEU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '69010281619540001' ,  '红旗渠(新版银河)' ,  '1' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_BRANDU"("BRAND_CODEU", "BRAND_NAMEU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '69010281605990001' ,  '红旗渠(硬银)' ,  '1' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."BI_BRANDU"("BRAND_CODEU", "BRAND_NAMEU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( '69010281692190001' ,  '黄金叶(硬帝豪)' ,  '1' ,  '' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
----插入新建配盘的配盘信息，好入库
insert into "C##FUSION"."BI_MATCH_PALLETU"("MATCH_PALLET_CODEU", "MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", "BRAND_CODESU", "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
( SELECT 'MES_'||"MATCH_PALLET_CODEU", 'MES_'||"MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", '69010281619540001', "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", SYSDATE, SYSDATE, SYS_GUID()
    FROM "C##FUSION"."BI_MATCH_PALLETU" WHERE "BRAND_CODESU"='161725'
);
insert into "C##FUSION"."BI_MATCH_PALLETU"("MATCH_PALLET_CODEU", "MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", "BRAND_CODESU", "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
( SELECT 'MES_'||"MATCH_PALLET_CODEU", 'MES_'||"MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", '69010281619540001', "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", SYSDATE, SYSDATE, SYS_GUID()
    FROM "C##FUSION"."BI_MATCH_PALLETU" WHERE "BRAND_CODESU"='166997'
);
insert into "C##FUSION"."BI_MATCH_PALLETU"("MATCH_PALLET_CODEU", "MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", "BRAND_CODESU", "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
( SELECT 'MES_'||"MATCH_PALLET_CODEU", 'MES_'||"MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", '69010281605990001', "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", SYSDATE, SYSDATE, SYS_GUID()
    FROM "C##FUSION"."BI_MATCH_PALLETU" WHERE "BRAND_CODESU"='161961'
);
insert into "C##FUSION"."BI_MATCH_PALLETU"("MATCH_PALLET_CODEU", "MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", "BRAND_CODESU", "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
( SELECT 'MES_'||"MATCH_PALLET_CODEU", 'MES_'||"MATCH_PALLET_NAMEU", "PALLET_TYPE_CODEU", "PALLET_TYPE_NAMEU", '69010281692190001', "BRAND_NAMESU", "MATCH_PALLET_STATUSU", "ACTIVEU", "REMARKU", SYSDATE, SYSDATE, SYS_GUID()
    FROM "C##FUSION"."BI_MATCH_PALLETU" WHERE "BRAND_CODESU"='160612'
);
----将配盘信息中的数据更新过来
insert into "C##FUSION"."BI_MATCH_PALLET_DETAILU"("IDU", "MATCH_PALLET_CODEU", "SERIALNUMBERU", "PRODUCT_CODEU", "WAREHOUSE_UNIT_CODEU", "WAREHOUSE_TRANSFER_RATEU", "WAREHOUSE_QUANTITYU", "WORKSHOP_UNIT_CODEU", "WORKSHOP_TRANSFER_RATEU", "WORKSHOP_QUANTITYU", "ACTIVEU", "REMARKU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
SELECT SYS_GUID(), 'MES_'||"MATCH_PALLET_CODEU", "SERIALNUMBERU", "PRODUCT_CODEU", "WAREHOUSE_UNIT_CODEU", "WAREHOUSE_TRANSFER_RATEU", "WAREHOUSE_QUANTITYU", "WORKSHOP_UNIT_CODEU", "WORKSHOP_TRANSFER_RATEU", "WORKSHOP_QUANTITYU", "ACTIVEU", "REMARKU",  SYSDATE ,  SYSDATE ,  SYS_GUID()
FROM "C##FUSION"."BI_MATCH_PALLET_DETAILU" WHERE MATCH_PALLET_CODEU IN (SELECT MATCH_PALLET_CODEU FROM BI_MATCH_PALLETU WHERE BI_MATCH_PALLETU.BRAND_CODESU IN ('161725', '166997', '161961', '160612'));

----对机组更新MES的机组编号作为外部机组编码
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200024488' where (("MACHINE_CODEU" =  'Z302' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200024487' where (("MACHINE_CODEU" =  'Z303' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200024483' where (("MACHINE_CODEU" =  'Z304' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200014828' where (("MACHINE_CODEU" =  'J101' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200020553' where (("MACHINE_CODEU" =  'J102' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200015341' where (("MACHINE_CODEU" =  'J103' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200016729' where (("MACHINE_CODEU" =  'J104' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200024031' where (("MACHINE_CODEU" =  'J105' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200003984' where (("MACHINE_CODEU" =  'J106' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200005982' where (("MACHINE_CODEU" =  'J107' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200024030' where (("MACHINE_CODEU" =  'J108' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200021256' where (("MACHINE_CODEU" =  'B201' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200021258' where (("MACHINE_CODEU" =  'B202' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200000345' where (("MACHINE_CODEU" =  'B203' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200020563' where (("MACHINE_CODEU" =  'B204' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200004500' where (("MACHINE_CODEU" =  'B205' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200020516' where (("MACHINE_CODEU" =  'B206' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200016250' where (("MACHINE_CODEU" =  'B207' ));
update "C##FUSION"."WM_MACHINEU" set "EXTERNAL_MACHINE_CODEU" =  '200200004137' where (("MACHINE_CODEU" =  'B208' ));
--*/
/* 后期如果一定要求要改正过来的话，因为修改了牌号，就需要更新这些数据表数据
SELECT * FROM WM_PALLETU;
SELECT * FROM WM_MACHINE_PALLETU;
SELECT * FROM BI_MATCH_PALLETU;
SELECT * FROM WM_MACHINE_CALLU;
SELECT * FROM WM_MACHINE_HANDOVERU;
--*/


--COMMIT;

