
update "C##FUSION"."WM_MACHINEU"
set "CLIENT_IPU" =  '127.0.0.11:90' , "EXTERNAL_MACHINE_CODEU" =  '' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("MACHINE_CODEU" IN(  'B201') ));
update "C##FUSION"."WM_MACHINEU"
set "CLIENT_IPU" =  '127.0.0.11:80' , "EXTERNAL_MACHINE_CODEU" =  '' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("MACHINE_CODEU" IN(  'J101') ));

update "C##FUSION"."WM_MACHINEU"
set "CLIENT_IPU" =  '127.0.0.10:90' , "EXTERNAL_MACHINE_CODEU" =  '' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("MACHINE_CODEU" IN(  'B204') )); 
update "C##FUSION"."WM_MACHINEU"
set "CLIENT_IPU" =  '127.0.0.1:80' , "EXTERNAL_MACHINE_CODEU" =  '' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("MACHINE_CODEU" IN(  'J104') ));

update "C##FUSION"."WM_MACHINEU"
set "CLIENT_IPU" =  '127.2.0.2:8090' , "EXTERNAL_MACHINE_CODEU" =  '' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("MACHINE_CODEU" IN(  'Z302') ));
update "C##FUSION"."WM_MACHINEU"
set "CLIENT_IPU" =  '127.2.0.2:8090' , "EXTERNAL_MACHINE_CODEU" =  '' , "UPDATE_TIMEU" =  SYSDATE , "ROW_VERSIONU" =  SYS_GUID()
where (("MACHINE_CODEU" IN(  'Z303') ));

--/*
delete from WM_PRODUCTION_PLANU;

----Ìí¼ÓÕâÐ©»ú×éµÄ¼Æ»®
insert into "C##FUSION"."WM_PRODUCTION_PLANU"("PRODUCTION_PLAN_NOU", "ORIGIN_PLAN_NOU", "PLAN_BEGIN_TIMEU", "PLAN_END_TIMEU", "MAKERU", "MAKE_TIMEU", "AUDITORU", "MOVE_BILL_NOU", "AUDIT_TIMEU", "PRODUCTION_PLAN_STATUSU", "PRODUCTION_PLAN_ORIGINU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( 'P201912260002_TEST' , null,  SYSDATE ,  SYSDATE + 1 ,  'admin' ,  SYSDATE ,  'admin' , null, SYSDATE,  '2' ,  '0' ,  SYSDATE ,  SYSDATE ,  SYS_GUID());
--insert into "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU"("IDU", "PRODUCTION_PLAN_NOU", "SERIAL_NUMBERU", "TEAM_CODEU", "TEAM_NAMEU", "MACHINE_CODEU", "MACHINE_NAMEU", "BRAND_CODEU", "BRAND_NAMEU", "ORIGIN_WORK_NOU", "PRODUCTION_PLAN_DETAIL_STATUSU", "PRODUCTION_BEGIN_TIMEU", "PRODUCTION_END_TIMEU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
--values ( SYS_GUID(),  'P201912260002_TEST' ,  '6' ,  'T0001' ,  '¼×°à' ,  'B204' ,  '4#°ü×°»ú' ,  '161725' ,  'ºìÆìÇþ£¨Ã¢¹û£©' , null,  '0' , null, null,  SYSDATE ,  SYSDATE ,  SYS_GUID());
insert into "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU"("IDU", "PRODUCTION_PLAN_NOU", "SERIAL_NUMBERU", "TEAM_CODEU", "TEAM_NAMEU", "MACHINE_CODEU", "MACHINE_NAMEU", "BRAND_CODEU", "BRAND_NAMEU", "ORIGIN_WORK_NOU", "PRODUCTION_PLAN_DETAIL_STATUSU", "PRODUCTION_BEGIN_TIMEU", "PRODUCTION_END_TIMEU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
values ( SYS_GUID(),  'P201912260002_TEST' ,  '2' ,  'T0001' ,  '¼×°à' ,  'J104' ,  '4#¾íÑÌ»ú' ,  '161725' ,  'ºìÆìÇþ£¨Ã¢¹û£©' , null,  '0' , null, null,  SYSDATE ,  SYSDATE ,  SYS_GUID());
--insert into "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU"("IDU", "PRODUCTION_PLAN_NOU", "SERIAL_NUMBERU", "TEAM_CODEU", "TEAM_NAMEU", "MACHINE_CODEU", "MACHINE_NAMEU", "BRAND_CODEU", "BRAND_NAMEU", "ORIGIN_WORK_NOU", "PRODUCTION_PLAN_DETAIL_STATUSU", "PRODUCTION_BEGIN_TIMEU", "PRODUCTION_END_TIMEU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
--values ( SYS_GUID(),  'P201912260002_TEST' ,  '5' ,  'T0001' ,  '¼×°à' ,  'Z302' ,  '2#×°·âÏä»ú' ,  '161725' ,  'ºìÆìÇþ£¨Ã¢¹û£©' , null,  '0' , null, null,  SYSDATE ,  SYSDATE ,  SYS_GUID());
--insert into "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU"("IDU", "PRODUCTION_PLAN_NOU", "SERIAL_NUMBERU", "TEAM_CODEU", "TEAM_NAMEU", "MACHINE_CODEU", "MACHINE_NAMEU", "BRAND_CODEU", "BRAND_NAMEU", "ORIGIN_WORK_NOU", "PRODUCTION_PLAN_DETAIL_STATUSU", "PRODUCTION_BEGIN_TIMEU", "PRODUCTION_END_TIMEU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
--values ( SYS_GUID(),  'P201912260002_TEST' ,  '4' ,  'T0001' ,  '¼×°à' ,  'Z303' ,  '3#×°·âÏä»ú' ,  '161725' ,  'ºìÆìÇþ£¨Ã¢¹û£©' , null,  '0' , null, null,  SYSDATE ,  SYSDATE ,  SYS_GUID());
--insert into "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU"("IDU", "PRODUCTION_PLAN_NOU", "SERIAL_NUMBERU", "TEAM_CODEU", "TEAM_NAMEU", "MACHINE_CODEU", "MACHINE_NAMEU", "BRAND_CODEU", "BRAND_NAMEU", "ORIGIN_WORK_NOU", "PRODUCTION_PLAN_DETAIL_STATUSU", "PRODUCTION_BEGIN_TIMEU", "PRODUCTION_END_TIMEU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
--values ( SYS_GUID(),  'P201912260002_TEST' ,  '1' ,  'T0001' ,  '¼×°à' ,  'J102' ,  '5#¾íÑÌ»ú' ,  '161725' ,  'ºìÆìÇþ£¨Ã¢¹û£©' , null,  '0' , null, null,  SYSDATE ,  SYSDATE ,  SYS_GUID());
--insert into "C##FUSION"."WM_PRODUCTION_PLAN_DETAILU"("IDU", "PRODUCTION_PLAN_NOU", "SERIAL_NUMBERU", "TEAM_CODEU", "TEAM_NAMEU", "MACHINE_CODEU", "MACHINE_NAMEU", "BRAND_CODEU", "BRAND_NAMEU", "ORIGIN_WORK_NOU", "PRODUCTION_PLAN_DETAIL_STATUSU", "PRODUCTION_BEGIN_TIMEU", "PRODUCTION_END_TIMEU", "CREATE_TIMEU", "UPDATE_TIMEU", "ROW_VERSIONU")
--values ( SYS_GUID(),  'P201912260002_TEST' ,  '3' ,  'T0001' ,  '¼×°à' ,  'B202' ,  '5#°ü×°»ú' ,  '161725' ,  'ºìÆìÇþ£¨Ã¢¹û£©' , null,  '0' , null, null,  SYSDATE ,  SYSDATE ,  SYS_GUID());

--*/
commit; 