
DROP TABLE BI_MODELU;
DELETE FROM BI_UNITU;
DELETE FROM BI_PRODUCTU;
DELETE FROM BI_PRODUCT_SIZEU;
DELETE FROM BI_PRODUCT_UNITU;
DELETE FROM BI_PRODUCT_BARCODEU;
DELETE FROM BI_FACTURERU;
DELETE FROM BI_PRODUCT_CATEGORYU;
DELETE FROM BI_PRODUCT_BREEDU;
DELETE FROM BI_PRODUCT_PATTERNU;
DELETE FROM BI_PRODUCT_GRADEU;
DELETE FROM BI_PRODUCT_ORIGINU;
DELETE FROM BI_CARGO_OWNERU;
--SELECT * FROM TM_TASKU;
update SYS_USERU SET PASSWORDU='thok@1234COM';
update BI_PRODUCTU SET PACK_TYPEU=1;
commit;