
--/*
------删除机组作业影响到的查询表
--删除机组呼叫信息
DELETE FROM WM_MACHINECALL;
DELETE FROM WM_MACHINECALLDETAIL;
--*/
--/*
--删除机组移交记录
DELETE FROM WM_MACHINEHANDOVERDETAIL;
DELETE FROM WM_MACHINEHANDOVER;
--删除机组余料返库信息
DELETE FROM WM_MACHINERETURN;
DELETE FROM WM_MACHINERETURNDETAIL;
--删除生产计划
DELETE FROM WM_PRODUCTIONPLAN;
DELETE FROM WM_PRODUCTIONPLANDETAIL;
--*/
--/*
--删除任务
DELETE FROM TM_TASK;
DELETE FROM TM_TASKDETAIL;
----删除配方
DELETE FROM BI_Formula;
DELETE FROM BI_FormulaDetail;
----删除配方出库
DELETE FROM WM_FormulaOut;
DELETE FROM WM_FormulaOutDetail;
------删除入库单据DELETE FROM WM_INBILLALLOTHISTORY;
DELETE FROM WM_INBILLALLOT;
DELETE FROM WM_INBILLDETAIL;
DELETE FROM WM_INBILLHISTORY;
DELETE FROM WM_INBILL;
------删除拼盘入库单据
DELETE FROM WM_ASSORTEDBILLDETAIL;
DELETE FROM WM_ASSORTEDBILL;
--删除移库单据
DELETE  FROM WM_MOVEBILLDETAIL;
DELETE  FROM WM_MOVEBILL;
--删除出库单据
DELETE FROM WM_OUTBILLALLOTHISTORY;
DELETE FROM WM_OUTBILLALLOT;
DELETE FROM WM_OUTBILLDETAILHISTORY;
DELETE FROM WM_OUTBILLDETAIL;
DELETE FROM WM_OUTBILLHISTORY;
DELETE FROM WM_OUTBILL;
----删除盘点单据
DELETE FROM WM_INVENTORYBILLDETAIL;
DELETE FROM WM_INVENTORYBILL;
----删除日结单据
DELETE FROM WM_DAILYBALANCEBILL;
--*/

----更新前2天之前的所有生产计划状态为已结单
--UPDATE WM_PRODUCTIONPLAN SET PRODUCTIONPLANSTATUS=3 WHERE CREATETIMEU <= TRUNC( GETDATE(), 'DD' ) -2;
----测试的时候该直接清空信息
--DELETE FROM WM_PRODUCTIONPLAN;
--删除机组下盘位细表
DELETE FROM WM_MACHINEPALLETDETAIL;
----更新所有机组中的盘位为空闲
update WM_MACHINEPALLET
set CURRENTBRANDCODE=  '' , CURRENTBRANDNAME=  '' 
    , CURRENTMATCHPALLETCODE=  '' , CURRENTMATCHPALLETNAME=  '' , CURRENTUNIQUEID=  '' , MACHINEPALLETSTATUS=  '0' 
    , UPDATETIME= GETDATE() , ROWVERSION=NEWID();
update TM_WORKPOSITION SET USEDQUANTITY=0 WHERE datalength(WorkPositionNo)=6;
----清空库存pallet信息，对应点：长度为6
UPDATE WM_PALLET SET MATCHPALLETCODE='', MATCHPALLETNAME='',UNIQUEID='',PRODUCTCOUNT=0,STORAGEQUANTITY=0,INFROZENQUANTITY=0,OUTFROZENQUANTITY=0
    ,PRODUCTPOSITION='',BRANDCODES='',BRANDNAMES='',PALLETTYPECODE='',PALLETTYPENAME='' WHERE datalength(LOCATIONCODE)=6;
--删除机组中的库存Storage信息
DELETE FROM WM_STORAGE WHERE datalength(LOCATIONCODE)=6;
--更改所有机组的已缓存量和已使用量
update TM_WORKPOSITION
set CACHEDQUANTITY=  '0' , USEDQUANTITY=  '0' , REMARK=  '' , UPDATETIME=  GETDATE() , ROWVERSION=  NEWID()
where (datalength(WORKPOSITIONNO)=6);


----更改盘点或其他业务影响到的库存信息
UPDATE WM_STORAGE SET LOCKTAG='';
UPDATE WM_PALLET SET PRODUCTPOSITION='10102' WHERE LOCATIONCODE='01-01-02';
UPDATE WM_PALLET SET STORAGESEQUENCE=abs(STORAGESEQUENCE) WHERE LOCATIONCODE='01-01-02';
----删除交互信息
DELETE FROM DMT_INTERACTIVEDATA;
DELETE FROM DMT_INTERACTIVEMANAGE;
DELETE FROM DMT_INTERACTIVEMESSAGE;
