
--/*
CREATE OR REPLACE PROCEDURE PRO_CLEAR_LOCATION 
(V_LOCATION_CODEU01 VARCHAR2)
AS
BEGIN
  ----清除货位库存
  UPDATE WM_LOCATIONU SET LOCATION_STATUSU='0' WHERE LOCATION_CODEU IN (V_LOCATION_CODEU01);  --限定高架库
  UPDATE WM_PALLETU SET MATCH_PALLET_CODEU='', MATCH_PALLET_NAMEU='',UNIQUE_IDU='',PRODUCT_COUNTU=0,STORAGE_QUANTITYU=0,IN_FROZEN_QUANTITYU=0,OUT_FROZEN_QUANTITYU=0
      ,PRODUCT_POSITIONU='',BRAND_CODESU='',BRAND_NAMESU='',PALLET_TYPE_CODEU='',PALLET_TYPE_NAMEU='' WHERE LOCATION_CODEU IN (V_LOCATION_CODEU01);
  DELETE FROM WM_STORAGEU WHERE LOCATION_CODEU IN (V_LOCATION_CODEU01);
END;
/
--/*
SET SERVEROUTPUT ON;
begin
  PRO_CLEAR_LOCATION(
    '01-06-03'
    --, '01-01-04'
    --, '01-13-03'
    --, '01-02-04'
  );
  commit;
end;
/