create or replace function F_01(
    IN_LOCATION_CODE varchar2
    ,IN_FACTURER_CODE varchar2
)
RETURN VARCHAR2
IS
    V_NUM_EX01 NUMBER;
    V_NUM_EX02 NUMBER;
    V_TEMP VARCHAR2(50);
    V_TEMP2 VARCHAR2(50);
    V_TEMP3 VARCHAR2(50);
    V_EXISTS_ROW NUMBER := 0;
    V_USED_PALLET_NUM NUMBER :=0;
BEGIN
  V_TEMP := '^_^';
  V_TEMP := IN_LOCATION_CODE;
    ----清空库存pallet信息，对应点：长度为6
    UPDATE WM_PALLETU SET MATCH_PALLET_CODEU='', MATCH_PALLET_NAMEU='',UNIQUE_IDU='',PRODUCT_COUNTU=0,STORAGE_QUANTITYU=0,IN_FROZEN_QUANTITYU=0,OUT_FROZEN_QUANTITYU=0
        ,PRODUCT_POSITIONU='',BRAND_CODESU='',BRAND_NAMESU='',PALLET_TYPE_CODEU='',PALLET_TYPE_NAMEU='' WHERE LOCATION_CODEU=V_TEMP;
    --删除机组中的库存Storage信息
    DELETE FROM WM_STORAGEU WHERE LOCATION_CODEU=V_TEMP;
  
  return '^_^';
END;
/
SET SERVEROUTPUT ON;
Declare
  ret varchar2(20);
Begin
  dbms_output.put_line('返回值：'||F_01('02-14-02', ''));
  COMMIT WORK;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
