 


// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String : `Data Source=E:\repository\FileSaveV1\LotterySite\SQLiteDatabase\Test.db`

		 
  

 


using System;
// using Dapper;
// using Dapper.Contrib.Extensions;

namespace FW.Single.Model
{
    /// <summary>
    /// A class which represents the ReplaceString table.
    /// </summary>
	// [Table("[ReplaceString]")]
	public partial class ReplaceString
	{
		/*  id  ActionCode  ActionName  ActionParamJson  GroupCode  TabCode  ReplaceDate  InputText  ResultText  */ 

		// [Key]
		public virtual int id { get; set; }
		public virtual string ActionCode { get; set; }
		public virtual string ActionName { get; set; }
		public virtual string ActionParamJson { get; set; }
		public virtual string GroupCode { get; set; }
		public virtual string TabCode { get; set; }
		public virtual string ReplaceDate { get; set; }
		public virtual string InputText { get; set; }
		public virtual string ResultText { get; set; }
	}

    /// <summary>
    /// A class which represents the sqlite_sequence table.
    /// </summary>
	// [Table("[sqlite_sequence]")]
	public partial class sqlitesequence
	{
		/*  name  seq  */ 

		public virtual string name { get; set; }
		public virtual string seq { get; set; }
	}

    /// <summary>
    /// A class which represents the LuckDraw table.
    /// </summary>
	// [Table("[LuckDraw]")]
	public partial class LuckDraw
	{
		/*  LdPrizeName  LdOpenID  ExhID  */ 

		public virtual string LdPrizeName { get; set; }
		public virtual string LdOpenID { get; set; }
		public virtual int? ExhID { get; set; }
	}

}

